/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  CreateReturnDto,
  GetAllReturnDto,
  GetOneReturnDto,
  Return,
  UpdateReturnDto,
  UpdateReturnStatusDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Create a new return
 */
export type createReturnResponse201 = {
  data: Return
  status: 201
}

export type createReturnResponse401 = {
  data: void
  status: 401
}

export type createReturnResponse403 = {
  data: void
  status: 403
}

export type createReturnResponseSuccess = createReturnResponse201 & {
  headers: Headers
}
export type createReturnResponseError = (
  | createReturnResponse401
  | createReturnResponse403
) & {
  headers: Headers
}

export type createReturnResponse =
  | createReturnResponseSuccess
  | createReturnResponseError

export const getCreateReturnUrl = () => {
  return `/returns`
}

export const createReturn = async (
  createReturnDto: CreateReturnDto,
  options?: RequestInit
): Promise<createReturnResponse> => {
  return customInstance<createReturnResponse>(getCreateReturnUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReturnDto)
  })
}

export const getCreateReturnMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createReturn>>,
    TError,
    { data: CreateReturnDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createReturn>>,
  TError,
  { data: CreateReturnDto },
  TContext
> => {
  const mutationKey = ['createReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createReturn>>,
    { data: CreateReturnDto }
  > = (props) => {
    const { data } = props ?? {}

    return createReturn(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof createReturn>>
>
export type CreateReturnMutationBody = CreateReturnDto
export type CreateReturnMutationError = ErrorType<void>

/**
 * @summary Create a new return
 */
export const useCreateReturn = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createReturn>>,
      TError,
      { data: CreateReturnDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createReturn>>,
  TError,
  { data: CreateReturnDto },
  TContext
> => {
  return useMutation(getCreateReturnMutationOptions(options), queryClient)
}
/**
 * @summary Get all returns
 */
export type getAllReturnsResponse200 = {
  data: GetAllReturnDto[]
  status: 200
}

export type getAllReturnsResponse401 = {
  data: void
  status: 401
}

export type getAllReturnsResponse403 = {
  data: void
  status: 403
}

export type getAllReturnsResponseSuccess = getAllReturnsResponse200 & {
  headers: Headers
}
export type getAllReturnsResponseError = (
  | getAllReturnsResponse401
  | getAllReturnsResponse403
) & {
  headers: Headers
}

export type getAllReturnsResponse =
  | getAllReturnsResponseSuccess
  | getAllReturnsResponseError

export const getGetAllReturnsUrl = () => {
  return `/returns`
}

export const getAllReturns = async (
  options?: RequestInit
): Promise<getAllReturnsResponse> => {
  return customInstance<getAllReturnsResponse>(getGetAllReturnsUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllReturnsQueryKey = () => {
  return [`/returns`] as const
}

export const getGetAllReturnsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllReturns>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllReturns>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllReturnsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllReturns>>> = ({
    signal
  }) => getAllReturns({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllReturns>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllReturnsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllReturns>>
>
export type GetAllReturnsQueryError = ErrorType<void>

export function useGetAllReturns<
  TData = Awaited<ReturnType<typeof getAllReturns>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllReturns>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllReturns>>,
          TError,
          Awaited<ReturnType<typeof getAllReturns>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllReturns<
  TData = Awaited<ReturnType<typeof getAllReturns>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllReturns>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllReturns>>,
          TError,
          Awaited<ReturnType<typeof getAllReturns>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllReturns<
  TData = Awaited<ReturnType<typeof getAllReturns>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllReturns>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all returns
 */

export function useGetAllReturns<
  TData = Awaited<ReturnType<typeof getAllReturns>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllReturns>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllReturnsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a specific return
 */
export type getOneReturnResponse200 = {
  data: GetOneReturnDto
  status: 200
}

export type getOneReturnResponse401 = {
  data: void
  status: 401
}

export type getOneReturnResponse403 = {
  data: void
  status: 403
}

export type getOneReturnResponse404 = {
  data: void
  status: 404
}

export type getOneReturnResponseSuccess = getOneReturnResponse200 & {
  headers: Headers
}
export type getOneReturnResponseError = (
  | getOneReturnResponse401
  | getOneReturnResponse403
  | getOneReturnResponse404
) & {
  headers: Headers
}

export type getOneReturnResponse =
  | getOneReturnResponseSuccess
  | getOneReturnResponseError

export const getGetOneReturnUrl = (id: string) => {
  return `/returns/${id}`
}

export const getOneReturn = async (
  id: string,
  options?: RequestInit
): Promise<getOneReturnResponse> => {
  return customInstance<getOneReturnResponse>(getGetOneReturnUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneReturnQueryKey = (id: string) => {
  return [`/returns/${id}`] as const
}

export const getGetOneReturnQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneReturn>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneReturn>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneReturnQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneReturn>>> = ({
    signal
  }) => getOneReturn(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneReturn>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneReturnQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneReturn>>
>
export type GetOneReturnQueryError = ErrorType<void>

export function useGetOneReturn<
  TData = Awaited<ReturnType<typeof getOneReturn>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneReturn>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneReturn>>,
          TError,
          Awaited<ReturnType<typeof getOneReturn>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneReturn<
  TData = Awaited<ReturnType<typeof getOneReturn>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneReturn>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneReturn>>,
          TError,
          Awaited<ReturnType<typeof getOneReturn>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneReturn<
  TData = Awaited<ReturnType<typeof getOneReturn>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneReturn>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific return
 */

export function useGetOneReturn<
  TData = Awaited<ReturnType<typeof getOneReturn>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneReturn>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneReturnQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a return
 */
export type updateReturnResponse200 = {
  data: Return
  status: 200
}

export type updateReturnResponse401 = {
  data: void
  status: 401
}

export type updateReturnResponse403 = {
  data: void
  status: 403
}

export type updateReturnResponseSuccess = updateReturnResponse200 & {
  headers: Headers
}
export type updateReturnResponseError = (
  | updateReturnResponse401
  | updateReturnResponse403
) & {
  headers: Headers
}

export type updateReturnResponse =
  | updateReturnResponseSuccess
  | updateReturnResponseError

export const getUpdateReturnUrl = (id: string) => {
  return `/returns/${id}`
}

export const updateReturn = async (
  id: string,
  updateReturnDto: UpdateReturnDto,
  options?: RequestInit
): Promise<updateReturnResponse> => {
  return customInstance<updateReturnResponse>(getUpdateReturnUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateReturnDto)
  })
}

export const getUpdateReturnMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateReturn>>,
    TError,
    { id: string; data: UpdateReturnDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateReturn>>,
  TError,
  { id: string; data: UpdateReturnDto },
  TContext
> => {
  const mutationKey = ['updateReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateReturn>>,
    { id: string; data: UpdateReturnDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateReturn(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateReturn>>
>
export type UpdateReturnMutationBody = UpdateReturnDto
export type UpdateReturnMutationError = ErrorType<void>

/**
 * @summary Update a return
 */
export const useUpdateReturn = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateReturn>>,
      TError,
      { id: string; data: UpdateReturnDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateReturn>>,
  TError,
  { id: string; data: UpdateReturnDto },
  TContext
> => {
  return useMutation(getUpdateReturnMutationOptions(options), queryClient)
}
/**
 * @summary Delete a return
 */
export type deleteReturnResponse204 = {
  data: Return
  status: 204
}

export type deleteReturnResponse401 = {
  data: void
  status: 401
}

export type deleteReturnResponse403 = {
  data: void
  status: 403
}

export type deleteReturnResponseSuccess = deleteReturnResponse204 & {
  headers: Headers
}
export type deleteReturnResponseError = (
  | deleteReturnResponse401
  | deleteReturnResponse403
) & {
  headers: Headers
}

export type deleteReturnResponse =
  | deleteReturnResponseSuccess
  | deleteReturnResponseError

export const getDeleteReturnUrl = (id: string) => {
  return `/returns/${id}`
}

export const deleteReturn = async (
  id: string,
  options?: RequestInit
): Promise<deleteReturnResponse> => {
  return customInstance<deleteReturnResponse>(getDeleteReturnUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

export const getDeleteReturnMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteReturn>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteReturn>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteReturn']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteReturn>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteReturn(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteReturnMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteReturn>>
>

export type DeleteReturnMutationError = ErrorType<void>

/**
 * @summary Delete a return
 */
export const useDeleteReturn = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteReturn>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteReturn>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteReturnMutationOptions(options), queryClient)
}
/**
 * @summary Update the status of a return
 */
export type updateReturnStatusResponse200 = {
  data: Return
  status: 200
}

export type updateReturnStatusResponse401 = {
  data: void
  status: 401
}

export type updateReturnStatusResponse403 = {
  data: void
  status: 403
}

export type updateReturnStatusResponseSuccess =
  updateReturnStatusResponse200 & {
    headers: Headers
  }
export type updateReturnStatusResponseError = (
  | updateReturnStatusResponse401
  | updateReturnStatusResponse403
) & {
  headers: Headers
}

export type updateReturnStatusResponse =
  | updateReturnStatusResponseSuccess
  | updateReturnStatusResponseError

export const getUpdateReturnStatusUrl = (id: string) => {
  return `/returns/${id}/status`
}

export const updateReturnStatus = async (
  id: string,
  updateReturnStatusDto: UpdateReturnStatusDto,
  options?: RequestInit
): Promise<updateReturnStatusResponse> => {
  return customInstance<updateReturnStatusResponse>(
    getUpdateReturnStatusUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateReturnStatusDto)
    }
  )
}

export const getUpdateReturnStatusMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateReturnStatus>>,
    TError,
    { id: string; data: UpdateReturnStatusDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateReturnStatus>>,
  TError,
  { id: string; data: UpdateReturnStatusDto },
  TContext
> => {
  const mutationKey = ['updateReturnStatus']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateReturnStatus>>,
    { id: string; data: UpdateReturnStatusDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateReturnStatus(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateReturnStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateReturnStatus>>
>
export type UpdateReturnStatusMutationBody = UpdateReturnStatusDto
export type UpdateReturnStatusMutationError = ErrorType<void>

/**
 * @summary Update the status of a return
 */
export const useUpdateReturnStatus = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateReturnStatus>>,
      TError,
      { id: string; data: UpdateReturnStatusDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateReturnStatus>>,
  TError,
  { id: string; data: UpdateReturnStatusDto },
  TContext
> => {
  return useMutation(getUpdateReturnStatusMutationOptions(options), queryClient)
}
