/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  CreateUserDto,
  UpdateUserDto,
  UpdateUserRoleDto,
  UpdateUserStatusDto,
  User,
  UserProductDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get all users
 */
export type getAllUsersResponse200 = {
  data: User[]
  status: 200
}

export type getAllUsersResponse401 = {
  data: void
  status: 401
}

export type getAllUsersResponse403 = {
  data: void
  status: 403
}

export type getAllUsersResponseSuccess = getAllUsersResponse200 & {
  headers: Headers
}
export type getAllUsersResponseError = (
  | getAllUsersResponse401
  | getAllUsersResponse403
) & {
  headers: Headers
}

export type getAllUsersResponse =
  | getAllUsersResponseSuccess
  | getAllUsersResponseError

export const getGetAllUsersUrl = () => {
  return `/users`
}

export const getAllUsers = async (
  options?: RequestInit
): Promise<getAllUsersResponse> => {
  return customInstance<getAllUsersResponse>(getGetAllUsersUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllUsersQueryKey = () => {
  return [`/users`] as const
}

export const getGetAllUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllUsersQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({
    signal
  }) => getAllUsers({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllUsers>>
>
export type GetAllUsersQueryError = ErrorType<void>

export function useGetAllUsers<
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllUsers<
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllUsers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllUsers<
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all users
 */

export function useGetAllUsers<
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get all pending users
 */
export type getAllPendingUsersResponse200 = {
  data: User[]
  status: 200
}

export type getAllPendingUsersResponse401 = {
  data: void
  status: 401
}

export type getAllPendingUsersResponse403 = {
  data: void
  status: 403
}

export type getAllPendingUsersResponseSuccess =
  getAllPendingUsersResponse200 & {
    headers: Headers
  }
export type getAllPendingUsersResponseError = (
  | getAllPendingUsersResponse401
  | getAllPendingUsersResponse403
) & {
  headers: Headers
}

export type getAllPendingUsersResponse =
  | getAllPendingUsersResponseSuccess
  | getAllPendingUsersResponseError

export const getGetAllPendingUsersUrl = () => {
  return `/users/pending`
}

export const getAllPendingUsers = async (
  options?: RequestInit
): Promise<getAllPendingUsersResponse> => {
  return customInstance<getAllPendingUsersResponse>(
    getGetAllPendingUsersUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getGetAllPendingUsersQueryKey = () => {
  return [`/users/pending`] as const
}

export const getGetAllPendingUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllPendingUsers>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAllPendingUsers>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllPendingUsersQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllPendingUsers>>
  > = ({ signal }) => getAllPendingUsers({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllPendingUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllPendingUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllPendingUsers>>
>
export type GetAllPendingUsersQueryError = ErrorType<void>

export function useGetAllPendingUsers<
  TData = Awaited<ReturnType<typeof getAllPendingUsers>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllPendingUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPendingUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllPendingUsers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllPendingUsers<
  TData = Awaited<ReturnType<typeof getAllPendingUsers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllPendingUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPendingUsers>>,
          TError,
          Awaited<ReturnType<typeof getAllPendingUsers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllPendingUsers<
  TData = Awaited<ReturnType<typeof getAllPendingUsers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllPendingUsers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all pending users
 */

export function useGetAllPendingUsers<
  TData = Awaited<ReturnType<typeof getAllPendingUsers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllPendingUsers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllPendingUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a specific user
 */
export type getOneUserResponse200 = {
  data: User
  status: 200
}

export type getOneUserResponse401 = {
  data: void
  status: 401
}

export type getOneUserResponse403 = {
  data: void
  status: 403
}

export type getOneUserResponse404 = {
  data: void
  status: 404
}

export type getOneUserResponseSuccess = getOneUserResponse200 & {
  headers: Headers
}
export type getOneUserResponseError = (
  | getOneUserResponse401
  | getOneUserResponse403
  | getOneUserResponse404
) & {
  headers: Headers
}

export type getOneUserResponse =
  | getOneUserResponseSuccess
  | getOneUserResponseError

export const getGetOneUserUrl = (id: string) => {
  return `/users/${id}`
}

export const getOneUser = async (
  id: string,
  options?: RequestInit
): Promise<getOneUserResponse> => {
  return customInstance<getOneUserResponse>(getGetOneUserUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneUserQueryKey = (id: string) => {
  return [`/users/${id}`] as const
}

export const getGetOneUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneUser>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneUser>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneUserQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneUser>>> = ({
    signal
  }) => getOneUser(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneUser>>
>
export type GetOneUserQueryError = ErrorType<void>

export function useGetOneUser<
  TData = Awaited<ReturnType<typeof getOneUser>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneUser>>,
          TError,
          Awaited<ReturnType<typeof getOneUser>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneUser<
  TData = Awaited<ReturnType<typeof getOneUser>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneUser>>,
          TError,
          Awaited<ReturnType<typeof getOneUser>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneUser<
  TData = Awaited<ReturnType<typeof getOneUser>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneUser>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific user
 */

export function useGetOneUser<
  TData = Awaited<ReturnType<typeof getOneUser>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneUser>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneUserQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a user
 */
export type updateUserResponse200 = {
  data: User
  status: 200
}

export type updateUserResponse401 = {
  data: void
  status: 401
}

export type updateUserResponse403 = {
  data: void
  status: 403
}

export type updateUserResponse404 = {
  data: void
  status: 404
}

export type updateUserResponseSuccess = updateUserResponse200 & {
  headers: Headers
}
export type updateUserResponseError = (
  | updateUserResponse401
  | updateUserResponse403
  | updateUserResponse404
) & {
  headers: Headers
}

export type updateUserResponse =
  | updateUserResponseSuccess
  | updateUserResponseError

export const getUpdateUserUrl = (id: string) => {
  return `/users/${id}`
}

export const updateUser = async (
  id: string,
  updateUserDto: UpdateUserDto,
  options?: RequestInit
): Promise<updateUserResponse> => {
  return customInstance<updateUserResponse>(getUpdateUserUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserDto)
  })
}

export const getUpdateUserMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    { id: string; data: UpdateUserDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  const mutationKey = ['updateUser']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUser>>,
    { id: string; data: UpdateUserDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateUser(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUser>>
>
export type UpdateUserMutationBody = UpdateUserDto
export type UpdateUserMutationError = ErrorType<void>

/**
 * @summary Update a user
 */
export const useUpdateUser = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUser>>,
      TError,
      { id: string; data: UpdateUserDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateUser>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  return useMutation(getUpdateUserMutationOptions(options), queryClient)
}
/**
 * @summary Delete a user
 */
export type deleteUserResponse204 = {
  data: void
  status: 204
}

export type deleteUserResponse401 = {
  data: void
  status: 401
}

export type deleteUserResponse403 = {
  data: void
  status: 403
}

export type deleteUserResponse404 = {
  data: void
  status: 404
}

export type deleteUserResponseSuccess = deleteUserResponse204 & {
  headers: Headers
}
export type deleteUserResponseError = (
  | deleteUserResponse401
  | deleteUserResponse403
  | deleteUserResponse404
) & {
  headers: Headers
}

export type deleteUserResponse =
  | deleteUserResponseSuccess
  | deleteUserResponseError

export const getDeleteUserUrl = (id: string) => {
  return `/users/${id}`
}

export const deleteUser = async (
  id: string,
  options?: RequestInit
): Promise<deleteUserResponse> => {
  return customInstance<deleteUserResponse>(getDeleteUserUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

export const getDeleteUserMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteUser']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUser>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteUser(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUser>>
>

export type DeleteUserMutationError = ErrorType<void>

/**
 * @summary Delete a user
 */
export const useDeleteUser = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteUserMutationOptions(options), queryClient)
}
/**
 * @summary Create a new user
 */
export type createUserResponse201 = {
  data: User
  status: 201
}

export type createUserResponse400 = {
  data: void
  status: 400
}

export type createUserResponseSuccess = createUserResponse201 & {
  headers: Headers
}
export type createUserResponseError = createUserResponse400 & {
  headers: Headers
}

export type createUserResponse =
  | createUserResponseSuccess
  | createUserResponseError

export const getCreateUserUrl = () => {
  return `/users/signup`
}

export const createUser = async (
  createUserDto: CreateUserDto,
  options?: RequestInit
): Promise<createUserResponse> => {
  return customInstance<createUserResponse>(getCreateUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUserDto)
  })
}

export const getCreateUserMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    { data: CreateUserDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUser>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  const mutationKey = ['createUser']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUser>>,
    { data: CreateUserDto }
  > = (props) => {
    const { data } = props ?? {}

    return createUser(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUser>>
>
export type CreateUserMutationBody = CreateUserDto
export type CreateUserMutationError = ErrorType<void>

/**
 * @summary Create a new user
 */
export const useCreateUser = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createUser>>,
      TError,
      { data: CreateUserDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createUser>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  return useMutation(getCreateUserMutationOptions(options), queryClient)
}
/**
 * @summary Update a user role
 */
export type updateUserRoleResponse200 = {
  data: User
  status: 200
}

export type updateUserRoleResponse401 = {
  data: void
  status: 401
}

export type updateUserRoleResponse403 = {
  data: void
  status: 403
}

export type updateUserRoleResponse404 = {
  data: void
  status: 404
}

export type updateUserRoleResponseSuccess = updateUserRoleResponse200 & {
  headers: Headers
}
export type updateUserRoleResponseError = (
  | updateUserRoleResponse401
  | updateUserRoleResponse403
  | updateUserRoleResponse404
) & {
  headers: Headers
}

export type updateUserRoleResponse =
  | updateUserRoleResponseSuccess
  | updateUserRoleResponseError

export const getUpdateUserRoleUrl = (id: string) => {
  return `/users/${id}/role`
}

export const updateUserRole = async (
  id: string,
  updateUserRoleDto: UpdateUserRoleDto,
  options?: RequestInit
): Promise<updateUserRoleResponse> => {
  return customInstance<updateUserRoleResponse>(getUpdateUserRoleUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserRoleDto)
  })
}

export const getUpdateUserRoleMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserRole>>,
    TError,
    { id: string; data: UpdateUserRoleDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserRole>>,
  TError,
  { id: string; data: UpdateUserRoleDto },
  TContext
> => {
  const mutationKey = ['updateUserRole']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserRole>>,
    { id: string; data: UpdateUserRoleDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateUserRole(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateUserRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserRole>>
>
export type UpdateUserRoleMutationBody = UpdateUserRoleDto
export type UpdateUserRoleMutationError = ErrorType<void>

/**
 * @summary Update a user role
 */
export const useUpdateUserRole = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserRole>>,
      TError,
      { id: string; data: UpdateUserRoleDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserRole>>,
  TError,
  { id: string; data: UpdateUserRoleDto },
  TContext
> => {
  return useMutation(getUpdateUserRoleMutationOptions(options), queryClient)
}
/**
 * @summary Disable a user
 */
export type disableUserResponse200 = {
  data: User
  status: 200
}

export type disableUserResponse401 = {
  data: void
  status: 401
}

export type disableUserResponse403 = {
  data: void
  status: 403
}

export type disableUserResponse404 = {
  data: void
  status: 404
}

export type disableUserResponseSuccess = disableUserResponse200 & {
  headers: Headers
}
export type disableUserResponseError = (
  | disableUserResponse401
  | disableUserResponse403
  | disableUserResponse404
) & {
  headers: Headers
}

export type disableUserResponse =
  | disableUserResponseSuccess
  | disableUserResponseError

export const getDisableUserUrl = (id: string) => {
  return `/users/${id}/disable`
}

export const disableUser = async (
  id: string,
  options?: RequestInit
): Promise<disableUserResponse> => {
  return customInstance<disableUserResponse>(getDisableUserUrl(id), {
    ...options,
    method: 'PATCH'
  })
}

export const getDisableUserMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof disableUser>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof disableUser>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['disableUser']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof disableUser>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return disableUser(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DisableUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof disableUser>>
>

export type DisableUserMutationError = ErrorType<void>

/**
 * @summary Disable a user
 */
export const useDisableUser = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof disableUser>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof disableUser>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDisableUserMutationOptions(options), queryClient)
}
/**
 * @summary Update a user status
 */
export type updateUserStatusResponse200 = {
  data: User
  status: 200
}

export type updateUserStatusResponse401 = {
  data: void
  status: 401
}

export type updateUserStatusResponse403 = {
  data: void
  status: 403
}

export type updateUserStatusResponse404 = {
  data: void
  status: 404
}

export type updateUserStatusResponseSuccess = updateUserStatusResponse200 & {
  headers: Headers
}
export type updateUserStatusResponseError = (
  | updateUserStatusResponse401
  | updateUserStatusResponse403
  | updateUserStatusResponse404
) & {
  headers: Headers
}

export type updateUserStatusResponse =
  | updateUserStatusResponseSuccess
  | updateUserStatusResponseError

export const getUpdateUserStatusUrl = (id: string) => {
  return `/users/${id}/status`
}

export const updateUserStatus = async (
  id: string,
  updateUserStatusDto: UpdateUserStatusDto,
  options?: RequestInit
): Promise<updateUserStatusResponse> => {
  return customInstance<updateUserStatusResponse>(getUpdateUserStatusUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserStatusDto)
  })
}

export const getUpdateUserStatusMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserStatus>>,
    TError,
    { id: string; data: UpdateUserStatusDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserStatus>>,
  TError,
  { id: string; data: UpdateUserStatusDto },
  TContext
> => {
  const mutationKey = ['updateUserStatus']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserStatus>>,
    { id: string; data: UpdateUserStatusDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateUserStatus(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateUserStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserStatus>>
>
export type UpdateUserStatusMutationBody = UpdateUserStatusDto
export type UpdateUserStatusMutationError = ErrorType<void>

/**
 * @summary Update a user status
 */
export const useUpdateUserStatus = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserStatus>>,
      TError,
      { id: string; data: UpdateUserStatusDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserStatus>>,
  TError,
  { id: string; data: UpdateUserStatusDto },
  TContext
> => {
  return useMutation(getUpdateUserStatusMutationOptions(options), queryClient)
}
/**
 * @summary Get user products
 */
export type getUserProductsResponse200 = {
  data: UserProductDto[]
  status: 200
}

export type getUserProductsResponse401 = {
  data: void
  status: 401
}

export type getUserProductsResponse403 = {
  data: void
  status: 403
}

export type getUserProductsResponse404 = {
  data: void
  status: 404
}

export type getUserProductsResponseSuccess = getUserProductsResponse200 & {
  headers: Headers
}
export type getUserProductsResponseError = (
  | getUserProductsResponse401
  | getUserProductsResponse403
  | getUserProductsResponse404
) & {
  headers: Headers
}

export type getUserProductsResponse =
  | getUserProductsResponseSuccess
  | getUserProductsResponseError

export const getGetUserProductsUrl = (id: string) => {
  return `/users/${id}/products`
}

export const getUserProducts = async (
  id: string,
  options?: RequestInit
): Promise<getUserProductsResponse> => {
  return customInstance<getUserProductsResponse>(getGetUserProductsUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetUserProductsQueryKey = (id: string) => {
  return [`/users/${id}/products`] as const
}

export const getGetUserProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserProducts>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProducts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetUserProductsQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProducts>>> = ({
    signal
  }) => getUserProducts(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserProducts>>
>
export type GetUserProductsQueryError = ErrorType<void>

export function useGetUserProducts<
  TData = Awaited<ReturnType<typeof getUserProducts>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProducts>>,
          TError,
          Awaited<ReturnType<typeof getUserProducts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserProducts<
  TData = Awaited<ReturnType<typeof getUserProducts>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProducts>>,
          TError,
          Awaited<ReturnType<typeof getUserProducts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetUserProducts<
  TData = Awaited<ReturnType<typeof getUserProducts>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProducts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get user products
 */

export function useGetUserProducts<
  TData = Awaited<ReturnType<typeof getUserProducts>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserProducts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetUserProductsQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
