/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  ChangePasswordDto,
  LoginDto,
  PasswordResetRequestResponseDto,
  RequestPasswordResetDto,
  ResetPasswordDto,
  ResetPasswordPageParams,
  VerifyDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Login
 */
export type loginResponse204 = {
  data: void
  status: 204
}

export type loginResponse401 = {
  data: void
  status: 401
}

export type loginResponseSuccess = loginResponse204 & {
  headers: Headers
}
export type loginResponseError = loginResponse401 & {
  headers: Headers
}

export type loginResponse = loginResponseSuccess | loginResponseError

export const getLoginUrl = () => {
  return `/auth/login`
}

export const login = async (
  loginDto: LoginDto,
  options?: RequestInit
): Promise<loginResponse> => {
  return customInstance<loginResponse>(getLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginDto)
  })
}

export const getLoginMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: LoginDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationKey = ['login']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: LoginDto }
  > = (props) => {
    const { data } = props ?? {}

    return login(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
export type LoginMutationBody = LoginDto
export type LoginMutationError = ErrorType<void>

/**
 * @summary Login
 */
export const useLogin = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof login>>,
      TError,
      { data: LoginDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  return useMutation(getLoginMutationOptions(options), queryClient)
}
/**
 * @summary Logout
 */
export type logoutResponse204 = {
  data: void
  status: 204
}

export type logoutResponseSuccess = logoutResponse204 & {
  headers: Headers
}
export type logoutResponse = logoutResponseSuccess

export const getLogoutUrl = () => {
  return `/auth/logout`
}

export const logout = async (
  options?: RequestInit
): Promise<logoutResponse> => {
  return customInstance<logoutResponse>(getLogoutUrl(), {
    ...options,
    method: 'POST'
  })
}

export const getLogoutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['logout']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    void
  > = () => {
    return logout(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>

export type LogoutMutationError = ErrorType<unknown>

/**
 * @summary Logout
 */
export const useLogout = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logout>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutMutationOptions(options), queryClient)
}
/**
 * @summary Forgot password
 */
export type forgotPasswordResponse201 = {
  data: PasswordResetRequestResponseDto
  status: 201
}

export type forgotPasswordResponse404 = {
  data: void
  status: 404
}

export type forgotPasswordResponseSuccess = forgotPasswordResponse201 & {
  headers: Headers
}
export type forgotPasswordResponseError = forgotPasswordResponse404 & {
  headers: Headers
}

export type forgotPasswordResponse =
  | forgotPasswordResponseSuccess
  | forgotPasswordResponseError

export const getForgotPasswordUrl = () => {
  return `/auth/forgot-password`
}

export const forgotPassword = async (
  requestPasswordResetDto: RequestPasswordResetDto,
  options?: RequestInit
): Promise<forgotPasswordResponse> => {
  return customInstance<forgotPasswordResponse>(getForgotPasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(requestPasswordResetDto)
  })
}

export const getForgotPasswordMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof forgotPassword>>,
    TError,
    { data: RequestPasswordResetDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof forgotPassword>>,
  TError,
  { data: RequestPasswordResetDto },
  TContext
> => {
  const mutationKey = ['forgotPassword']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof forgotPassword>>,
    { data: RequestPasswordResetDto }
  > = (props) => {
    const { data } = props ?? {}

    return forgotPassword(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof forgotPassword>>
>
export type ForgotPasswordMutationBody = RequestPasswordResetDto
export type ForgotPasswordMutationError = ErrorType<void>

/**
 * @summary Forgot password
 */
export const useForgotPassword = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof forgotPassword>>,
      TError,
      { data: RequestPasswordResetDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof forgotPassword>>,
  TError,
  { data: RequestPasswordResetDto },
  TContext
> => {
  return useMutation(getForgotPasswordMutationOptions(options), queryClient)
}
/**
 * @summary List password reset requests (Admin only)
 */
export type listPasswordResetRequestsResponse200 = {
  data: PasswordResetRequestResponseDto[]
  status: 200
}

export type listPasswordResetRequestsResponseSuccess =
  listPasswordResetRequestsResponse200 & {
    headers: Headers
  }
export type listPasswordResetRequestsResponse =
  listPasswordResetRequestsResponseSuccess

export const getListPasswordResetRequestsUrl = () => {
  return `/auth/password-reset-requests`
}

export const listPasswordResetRequests = async (
  options?: RequestInit
): Promise<listPasswordResetRequestsResponse> => {
  return customInstance<listPasswordResetRequestsResponse>(
    getListPasswordResetRequestsUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getListPasswordResetRequestsQueryKey = () => {
  return [`/auth/password-reset-requests`] as const
}

export const getListPasswordResetRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPasswordResetRequests>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof listPasswordResetRequests>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getListPasswordResetRequestsQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPasswordResetRequests>>
  > = ({ signal }) => listPasswordResetRequests({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPasswordResetRequests>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPasswordResetRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPasswordResetRequests>>
>
export type ListPasswordResetRequestsQueryError = ErrorType<unknown>

export function useListPasswordResetRequests<
  TData = Awaited<ReturnType<typeof listPasswordResetRequests>>,
  TError = ErrorType<unknown>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPasswordResetRequests>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPasswordResetRequests>>,
          TError,
          Awaited<ReturnType<typeof listPasswordResetRequests>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListPasswordResetRequests<
  TData = Awaited<ReturnType<typeof listPasswordResetRequests>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPasswordResetRequests>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPasswordResetRequests>>,
          TError,
          Awaited<ReturnType<typeof listPasswordResetRequests>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useListPasswordResetRequests<
  TData = Awaited<ReturnType<typeof listPasswordResetRequests>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPasswordResetRequests>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary List password reset requests (Admin only)
 */

export function useListPasswordResetRequests<
  TData = Awaited<ReturnType<typeof listPasswordResetRequests>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listPasswordResetRequests>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getListPasswordResetRequestsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Approve password reset request (Admin only)
 */
export type approvePasswordResetRequestResponse204 = {
  data: void
  status: 204
}

export type approvePasswordResetRequestResponse404 = {
  data: void
  status: 404
}

export type approvePasswordResetRequestResponseSuccess =
  approvePasswordResetRequestResponse204 & {
    headers: Headers
  }
export type approvePasswordResetRequestResponseError =
  approvePasswordResetRequestResponse404 & {
    headers: Headers
  }

export type approvePasswordResetRequestResponse =
  | approvePasswordResetRequestResponseSuccess
  | approvePasswordResetRequestResponseError

export const getApprovePasswordResetRequestUrl = (id: string) => {
  return `/auth/password-reset-requests/${id}/approve`
}

export const approvePasswordResetRequest = async (
  id: string,
  options?: RequestInit
): Promise<approvePasswordResetRequestResponse> => {
  return customInstance<approvePasswordResetRequestResponse>(
    getApprovePasswordResetRequestUrl(id),
    {
      ...options,
      method: 'PATCH'
    }
  )
}

export const getApprovePasswordResetRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof approvePasswordResetRequest>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof approvePasswordResetRequest>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['approvePasswordResetRequest']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approvePasswordResetRequest>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return approvePasswordResetRequest(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ApprovePasswordResetRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof approvePasswordResetRequest>>
>

export type ApprovePasswordResetRequestMutationError = ErrorType<void>

/**
 * @summary Approve password reset request (Admin only)
 */
export const useApprovePasswordResetRequest = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof approvePasswordResetRequest>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof approvePasswordResetRequest>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getApprovePasswordResetRequestMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Reject password reset request (Admin only)
 */
export type rejectPasswordResetRequestResponse204 = {
  data: void
  status: 204
}

export type rejectPasswordResetRequestResponse404 = {
  data: void
  status: 404
}

export type rejectPasswordResetRequestResponseSuccess =
  rejectPasswordResetRequestResponse204 & {
    headers: Headers
  }
export type rejectPasswordResetRequestResponseError =
  rejectPasswordResetRequestResponse404 & {
    headers: Headers
  }

export type rejectPasswordResetRequestResponse =
  | rejectPasswordResetRequestResponseSuccess
  | rejectPasswordResetRequestResponseError

export const getRejectPasswordResetRequestUrl = (id: string) => {
  return `/auth/password-reset-requests/${id}/reject`
}

export const rejectPasswordResetRequest = async (
  id: string,
  options?: RequestInit
): Promise<rejectPasswordResetRequestResponse> => {
  return customInstance<rejectPasswordResetRequestResponse>(
    getRejectPasswordResetRequestUrl(id),
    {
      ...options,
      method: 'PATCH'
    }
  )
}

export const getRejectPasswordResetRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rejectPasswordResetRequest>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof rejectPasswordResetRequest>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['rejectPasswordResetRequest']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rejectPasswordResetRequest>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return rejectPasswordResetRequest(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RejectPasswordResetRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof rejectPasswordResetRequest>>
>

export type RejectPasswordResetRequestMutationError = ErrorType<void>

/**
 * @summary Reject password reset request (Admin only)
 */
export const useRejectPasswordResetRequest = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rejectPasswordResetRequest>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof rejectPasswordResetRequest>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getRejectPasswordResetRequestMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Reset password
 */
export type resetPasswordResponse204 = {
  data: void
  status: 204
}

export type resetPasswordResponse400 = {
  data: void
  status: 400
}

export type resetPasswordResponseSuccess = resetPasswordResponse204 & {
  headers: Headers
}
export type resetPasswordResponseError = resetPasswordResponse400 & {
  headers: Headers
}

export type resetPasswordResponse =
  | resetPasswordResponseSuccess
  | resetPasswordResponseError

export const getResetPasswordUrl = () => {
  return `/auth/reset-password`
}

export const resetPassword = async (
  resetPasswordDto: ResetPasswordDto,
  options?: RequestInit
): Promise<resetPasswordResponse> => {
  return customInstance<resetPasswordResponse>(getResetPasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(resetPasswordDto)
  })
}

export const getResetPasswordMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetPassword>>,
    TError,
    { data: ResetPasswordDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { data: ResetPasswordDto },
  TContext
> => {
  const mutationKey = ['resetPassword']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetPassword>>,
    { data: ResetPasswordDto }
  > = (props) => {
    const { data } = props ?? {}

    return resetPassword(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResetPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof resetPassword>>
>
export type ResetPasswordMutationBody = ResetPasswordDto
export type ResetPasswordMutationError = ErrorType<void>

/**
 * @summary Reset password
 */
export const useResetPassword = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resetPassword>>,
      TError,
      { data: ResetPasswordDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { data: ResetPasswordDto },
  TContext
> => {
  return useMutation(getResetPasswordMutationOptions(options), queryClient)
}
/**
 * @summary Change password
 */
export type changePasswordResponse204 = {
  data: void
  status: 204
}

export type changePasswordResponse401 = {
  data: void
  status: 401
}

export type changePasswordResponse404 = {
  data: void
  status: 404
}

export type changePasswordResponseSuccess = changePasswordResponse204 & {
  headers: Headers
}
export type changePasswordResponseError = (
  | changePasswordResponse401
  | changePasswordResponse404
) & {
  headers: Headers
}

export type changePasswordResponse =
  | changePasswordResponseSuccess
  | changePasswordResponseError

export const getChangePasswordUrl = () => {
  return `/auth/change-password`
}

export const changePassword = async (
  changePasswordDto: ChangePasswordDto,
  options?: RequestInit
): Promise<changePasswordResponse> => {
  return customInstance<changePasswordResponse>(getChangePasswordUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(changePasswordDto)
  })
}

export const getChangePasswordMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changePassword>>,
    TError,
    { data: ChangePasswordDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof changePassword>>,
  TError,
  { data: ChangePasswordDto },
  TContext
> => {
  const mutationKey = ['changePassword']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changePassword>>,
    { data: ChangePasswordDto }
  > = (props) => {
    const { data } = props ?? {}

    return changePassword(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof changePassword>>
>
export type ChangePasswordMutationBody = ChangePasswordDto
export type ChangePasswordMutationError = ErrorType<void>

/**
 * @summary Change password
 */
export const useChangePassword = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changePassword>>,
      TError,
      { data: ChangePasswordDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof changePassword>>,
  TError,
  { data: ChangePasswordDto },
  TContext
> => {
  return useMutation(getChangePasswordMutationOptions(options), queryClient)
}
/**
 * @summary Reset password page (Development only)
 */
export type resetPasswordPageResponse200 = {
  data: void
  status: 200
}

export type resetPasswordPageResponseSuccess = resetPasswordPageResponse200 & {
  headers: Headers
}
export type resetPasswordPageResponse = resetPasswordPageResponseSuccess

export const getResetPasswordPageUrl = (params: ResetPasswordPageParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/auth/reset-password-page?${stringifiedParams}`
    : `/auth/reset-password-page`
}

export const resetPasswordPage = async (
  params: ResetPasswordPageParams,
  options?: RequestInit
): Promise<resetPasswordPageResponse> => {
  return customInstance<resetPasswordPageResponse>(
    getResetPasswordPageUrl(params),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getResetPasswordPageQueryKey = (
  params?: ResetPasswordPageParams
) => {
  return [`/auth/reset-password-page`, ...(params ? [params] : [])] as const
}

export const getResetPasswordPageQueryOptions = <
  TData = Awaited<ReturnType<typeof resetPasswordPage>>,
  TError = ErrorType<unknown>
>(
  params: ResetPasswordPageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resetPasswordPage>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getResetPasswordPageQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof resetPasswordPage>>
  > = ({ signal }) => resetPasswordPage(params, { signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof resetPasswordPage>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResetPasswordPageQueryResult = NonNullable<
  Awaited<ReturnType<typeof resetPasswordPage>>
>
export type ResetPasswordPageQueryError = ErrorType<unknown>

export function useResetPasswordPage<
  TData = Awaited<ReturnType<typeof resetPasswordPage>>,
  TError = ErrorType<unknown>
>(
  params: ResetPasswordPageParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resetPasswordPage>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resetPasswordPage>>,
          TError,
          Awaited<ReturnType<typeof resetPasswordPage>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useResetPasswordPage<
  TData = Awaited<ReturnType<typeof resetPasswordPage>>,
  TError = ErrorType<unknown>
>(
  params: ResetPasswordPageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resetPasswordPage>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resetPasswordPage>>,
          TError,
          Awaited<ReturnType<typeof resetPasswordPage>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useResetPasswordPage<
  TData = Awaited<ReturnType<typeof resetPasswordPage>>,
  TError = ErrorType<unknown>
>(
  params: ResetPasswordPageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resetPasswordPage>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Reset password page (Development only)
 */

export function useResetPasswordPage<
  TData = Awaited<ReturnType<typeof resetPasswordPage>>,
  TError = ErrorType<unknown>
>(
  params: ResetPasswordPageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof resetPasswordPage>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getResetPasswordPageQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type authGetStylesResponse200 = {
  data: void
  status: 200
}

export type authGetStylesResponseSuccess = authGetStylesResponse200 & {
  headers: Headers
}
export type authGetStylesResponse = authGetStylesResponseSuccess

export const getAuthGetStylesUrl = () => {
  return `/auth/reset-password-page/styles.css`
}

export const authGetStyles = async (
  options?: RequestInit
): Promise<authGetStylesResponse> => {
  return customInstance<authGetStylesResponse>(getAuthGetStylesUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getAuthGetStylesQueryKey = () => {
  return [`/auth/reset-password-page/styles.css`] as const
}

export const getAuthGetStylesQueryOptions = <
  TData = Awaited<ReturnType<typeof authGetStyles>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authGetStyles>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAuthGetStylesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authGetStyles>>> = ({
    signal
  }) => authGetStyles({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authGetStyles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthGetStylesQueryResult = NonNullable<
  Awaited<ReturnType<typeof authGetStyles>>
>
export type AuthGetStylesQueryError = ErrorType<unknown>

export function useAuthGetStyles<
  TData = Awaited<ReturnType<typeof authGetStyles>>,
  TError = ErrorType<unknown>
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authGetStyles>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetStyles>>,
          TError,
          Awaited<ReturnType<typeof authGetStyles>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthGetStyles<
  TData = Awaited<ReturnType<typeof authGetStyles>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authGetStyles>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetStyles>>,
          TError,
          Awaited<ReturnType<typeof authGetStyles>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthGetStyles<
  TData = Awaited<ReturnType<typeof authGetStyles>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authGetStyles>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useAuthGetStyles<
  TData = Awaited<ReturnType<typeof authGetStyles>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authGetStyles>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAuthGetStylesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export type authGetScriptResponse200 = {
  data: void
  status: 200
}

export type authGetScriptResponseSuccess = authGetScriptResponse200 & {
  headers: Headers
}
export type authGetScriptResponse = authGetScriptResponseSuccess

export const getAuthGetScriptUrl = () => {
  return `/auth/reset-password-page/script.js`
}

export const authGetScript = async (
  options?: RequestInit
): Promise<authGetScriptResponse> => {
  return customInstance<authGetScriptResponse>(getAuthGetScriptUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getAuthGetScriptQueryKey = () => {
  return [`/auth/reset-password-page/script.js`] as const
}

export const getAuthGetScriptQueryOptions = <
  TData = Awaited<ReturnType<typeof authGetScript>>,
  TError = ErrorType<unknown>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authGetScript>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getAuthGetScriptQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authGetScript>>> = ({
    signal
  }) => authGetScript({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authGetScript>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthGetScriptQueryResult = NonNullable<
  Awaited<ReturnType<typeof authGetScript>>
>
export type AuthGetScriptQueryError = ErrorType<unknown>

export function useAuthGetScript<
  TData = Awaited<ReturnType<typeof authGetScript>>,
  TError = ErrorType<unknown>
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authGetScript>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetScript>>,
          TError,
          Awaited<ReturnType<typeof authGetScript>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthGetScript<
  TData = Awaited<ReturnType<typeof authGetScript>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authGetScript>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetScript>>,
          TError,
          Awaited<ReturnType<typeof authGetScript>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useAuthGetScript<
  TData = Awaited<ReturnType<typeof authGetScript>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authGetScript>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}

export function useAuthGetScript<
  TData = Awaited<ReturnType<typeof authGetScript>>,
  TError = ErrorType<unknown>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authGetScript>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getAuthGetScriptQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Verify JWT token
 */
export type verifyTokenResponse200 = {
  data: VerifyDto
  status: 200
}

export type verifyTokenResponse401 = {
  data: void
  status: 401
}

export type verifyTokenResponseSuccess = verifyTokenResponse200 & {
  headers: Headers
}
export type verifyTokenResponseError = verifyTokenResponse401 & {
  headers: Headers
}

export type verifyTokenResponse =
  | verifyTokenResponseSuccess
  | verifyTokenResponseError

export const getVerifyTokenUrl = () => {
  return `/auth/verify`
}

export const verifyToken = async (
  options?: RequestInit
): Promise<verifyTokenResponse> => {
  return customInstance<verifyTokenResponse>(getVerifyTokenUrl(), {
    ...options,
    method: 'POST'
  })
}

export const getVerifyTokenMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof verifyToken>>,
    TError,
    void,
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof verifyToken>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['verifyToken']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof verifyToken>>,
    void
  > = () => {
    return verifyToken(requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type VerifyTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof verifyToken>>
>

export type VerifyTokenMutationError = ErrorType<void>

/**
 * @summary Verify JWT token
 */
export const useVerifyToken = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof verifyToken>>,
      TError,
      void,
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof verifyToken>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getVerifyTokenMutationOptions(options), queryClient)
}
