/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  CreateProductModelDto,
  ProductModel,
  UpdateProductModelDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get Cloudinary upload signature
 */
export type getCloudinarySignatureResponse200 = {
  data: void
  status: 200
}

export type getCloudinarySignatureResponse401 = {
  data: void
  status: 401
}

export type getCloudinarySignatureResponse403 = {
  data: void
  status: 403
}

export type getCloudinarySignatureResponseSuccess =
  getCloudinarySignatureResponse200 & {
    headers: Headers
  }
export type getCloudinarySignatureResponseError = (
  | getCloudinarySignatureResponse401
  | getCloudinarySignatureResponse403
) & {
  headers: Headers
}

export type getCloudinarySignatureResponse =
  | getCloudinarySignatureResponseSuccess
  | getCloudinarySignatureResponseError

export const getGetCloudinarySignatureUrl = () => {
  return `/product-models/cloudinary-signature`
}

export const getCloudinarySignature = async (
  options?: RequestInit
): Promise<getCloudinarySignatureResponse> => {
  return customInstance<getCloudinarySignatureResponse>(
    getGetCloudinarySignatureUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getGetCloudinarySignatureQueryKey = () => {
  return [`/product-models/cloudinary-signature`] as const
}

export const getGetCloudinarySignatureQueryOptions = <
  TData = Awaited<ReturnType<typeof getCloudinarySignature>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCloudinarySignature>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCloudinarySignatureQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCloudinarySignature>>
  > = ({ signal }) => getCloudinarySignature({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCloudinarySignature>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCloudinarySignatureQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCloudinarySignature>>
>
export type GetCloudinarySignatureQueryError = ErrorType<void>

export function useGetCloudinarySignature<
  TData = Awaited<ReturnType<typeof getCloudinarySignature>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCloudinarySignature>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCloudinarySignature>>,
          TError,
          Awaited<ReturnType<typeof getCloudinarySignature>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCloudinarySignature<
  TData = Awaited<ReturnType<typeof getCloudinarySignature>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCloudinarySignature>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCloudinarySignature>>,
          TError,
          Awaited<ReturnType<typeof getCloudinarySignature>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCloudinarySignature<
  TData = Awaited<ReturnType<typeof getCloudinarySignature>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCloudinarySignature>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Cloudinary upload signature
 */

export function useGetCloudinarySignature<
  TData = Awaited<ReturnType<typeof getCloudinarySignature>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCloudinarySignature>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetCloudinarySignatureQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get all product models
 */
export type getAllProductModelsResponse200 = {
  data: ProductModel[]
  status: 200
}

export type getAllProductModelsResponse401 = {
  data: void
  status: 401
}

export type getAllProductModelsResponse403 = {
  data: void
  status: 403
}

export type getAllProductModelsResponseSuccess =
  getAllProductModelsResponse200 & {
    headers: Headers
  }
export type getAllProductModelsResponseError = (
  | getAllProductModelsResponse401
  | getAllProductModelsResponse403
) & {
  headers: Headers
}

export type getAllProductModelsResponse =
  | getAllProductModelsResponseSuccess
  | getAllProductModelsResponseError

export const getGetAllProductModelsUrl = () => {
  return `/product-models`
}

export const getAllProductModels = async (
  options?: RequestInit
): Promise<getAllProductModelsResponse> => {
  return customInstance<getAllProductModelsResponse>(
    getGetAllProductModelsUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getGetAllProductModelsQueryKey = () => {
  return [`/product-models`] as const
}

export const getGetAllProductModelsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllProductModels>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAllProductModels>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllProductModelsQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllProductModels>>
  > = ({ signal }) => getAllProductModels({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllProductModels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProductModelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllProductModels>>
>
export type GetAllProductModelsQueryError = ErrorType<void>

export function useGetAllProductModels<
  TData = Awaited<ReturnType<typeof getAllProductModels>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllProductModels>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProductModels>>,
          TError,
          Awaited<ReturnType<typeof getAllProductModels>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllProductModels<
  TData = Awaited<ReturnType<typeof getAllProductModels>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllProductModels>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProductModels>>,
          TError,
          Awaited<ReturnType<typeof getAllProductModels>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllProductModels<
  TData = Awaited<ReturnType<typeof getAllProductModels>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllProductModels>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all product models
 */

export function useGetAllProductModels<
  TData = Awaited<ReturnType<typeof getAllProductModels>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllProductModels>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllProductModelsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Create a new product model
 */
export type createProductModelResponse201 = {
  data: ProductModel
  status: 201
}

export type createProductModelResponse401 = {
  data: void
  status: 401
}

export type createProductModelResponse403 = {
  data: void
  status: 403
}

export type createProductModelResponseSuccess =
  createProductModelResponse201 & {
    headers: Headers
  }
export type createProductModelResponseError = (
  | createProductModelResponse401
  | createProductModelResponse403
) & {
  headers: Headers
}

export type createProductModelResponse =
  | createProductModelResponseSuccess
  | createProductModelResponseError

export const getCreateProductModelUrl = () => {
  return `/product-models`
}

export const createProductModel = async (
  createProductModelDto: CreateProductModelDto,
  options?: RequestInit
): Promise<createProductModelResponse> => {
  return customInstance<createProductModelResponse>(
    getCreateProductModelUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createProductModelDto)
    }
  )
}

export const getCreateProductModelMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProductModel>>,
    TError,
    { data: CreateProductModelDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProductModel>>,
  TError,
  { data: CreateProductModelDto },
  TContext
> => {
  const mutationKey = ['createProductModel']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProductModel>>,
    { data: CreateProductModelDto }
  > = (props) => {
    const { data } = props ?? {}

    return createProductModel(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateProductModelMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProductModel>>
>
export type CreateProductModelMutationBody = CreateProductModelDto
export type CreateProductModelMutationError = ErrorType<void>

/**
 * @summary Create a new product model
 */
export const useCreateProductModel = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProductModel>>,
      TError,
      { data: CreateProductModelDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createProductModel>>,
  TError,
  { data: CreateProductModelDto },
  TContext
> => {
  return useMutation(getCreateProductModelMutationOptions(options), queryClient)
}
/**
 * @summary Get a specific product model
 */
export type getOneProductModelResponse200 = {
  data: ProductModel
  status: 200
}

export type getOneProductModelResponse401 = {
  data: void
  status: 401
}

export type getOneProductModelResponse403 = {
  data: void
  status: 403
}

export type getOneProductModelResponse404 = {
  data: void
  status: 404
}

export type getOneProductModelResponseSuccess =
  getOneProductModelResponse200 & {
    headers: Headers
  }
export type getOneProductModelResponseError = (
  | getOneProductModelResponse401
  | getOneProductModelResponse403
  | getOneProductModelResponse404
) & {
  headers: Headers
}

export type getOneProductModelResponse =
  | getOneProductModelResponseSuccess
  | getOneProductModelResponseError

export const getGetOneProductModelUrl = (id: string) => {
  return `/product-models/${id}`
}

export const getOneProductModel = async (
  id: string,
  options?: RequestInit
): Promise<getOneProductModelResponse> => {
  return customInstance<getOneProductModelResponse>(
    getGetOneProductModelUrl(id),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getGetOneProductModelQueryKey = (id: string) => {
  return [`/product-models/${id}`] as const
}

export const getGetOneProductModelQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneProductModel>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneProductModel>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneProductModelQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOneProductModel>>
  > = ({ signal }) => getOneProductModel(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneProductModel>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneProductModelQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneProductModel>>
>
export type GetOneProductModelQueryError = ErrorType<void>

export function useGetOneProductModel<
  TData = Awaited<ReturnType<typeof getOneProductModel>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneProductModel>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneProductModel>>,
          TError,
          Awaited<ReturnType<typeof getOneProductModel>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneProductModel<
  TData = Awaited<ReturnType<typeof getOneProductModel>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneProductModel>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneProductModel>>,
          TError,
          Awaited<ReturnType<typeof getOneProductModel>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneProductModel<
  TData = Awaited<ReturnType<typeof getOneProductModel>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneProductModel>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific product model
 */

export function useGetOneProductModel<
  TData = Awaited<ReturnType<typeof getOneProductModel>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneProductModel>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneProductModelQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a product model
 */
export type updateProductModelResponse200 = {
  data: ProductModel
  status: 200
}

export type updateProductModelResponse401 = {
  data: void
  status: 401
}

export type updateProductModelResponse403 = {
  data: void
  status: 403
}

export type updateProductModelResponseSuccess =
  updateProductModelResponse200 & {
    headers: Headers
  }
export type updateProductModelResponseError = (
  | updateProductModelResponse401
  | updateProductModelResponse403
) & {
  headers: Headers
}

export type updateProductModelResponse =
  | updateProductModelResponseSuccess
  | updateProductModelResponseError

export const getUpdateProductModelUrl = (id: string) => {
  return `/product-models/${id}`
}

export const updateProductModel = async (
  id: string,
  updateProductModelDto: UpdateProductModelDto,
  options?: RequestInit
): Promise<updateProductModelResponse> => {
  return customInstance<updateProductModelResponse>(
    getUpdateProductModelUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateProductModelDto)
    }
  )
}

export const getUpdateProductModelMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProductModel>>,
    TError,
    { id: string; data: UpdateProductModelDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProductModel>>,
  TError,
  { id: string; data: UpdateProductModelDto },
  TContext
> => {
  const mutationKey = ['updateProductModel']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProductModel>>,
    { id: string; data: UpdateProductModelDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateProductModel(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateProductModelMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProductModel>>
>
export type UpdateProductModelMutationBody = UpdateProductModelDto
export type UpdateProductModelMutationError = ErrorType<void>

/**
 * @summary Update a product model
 */
export const useUpdateProductModel = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProductModel>>,
      TError,
      { id: string; data: UpdateProductModelDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateProductModel>>,
  TError,
  { id: string; data: UpdateProductModelDto },
  TContext
> => {
  return useMutation(getUpdateProductModelMutationOptions(options), queryClient)
}
/**
 * @summary Delete a product model
 */
export type deleteProductModelResponse204 = {
  data: void
  status: 204
}

export type deleteProductModelResponse401 = {
  data: void
  status: 401
}

export type deleteProductModelResponse403 = {
  data: void
  status: 403
}

export type deleteProductModelResponseSuccess =
  deleteProductModelResponse204 & {
    headers: Headers
  }
export type deleteProductModelResponseError = (
  | deleteProductModelResponse401
  | deleteProductModelResponse403
) & {
  headers: Headers
}

export type deleteProductModelResponse =
  | deleteProductModelResponseSuccess
  | deleteProductModelResponseError

export const getDeleteProductModelUrl = (id: string) => {
  return `/product-models/${id}`
}

export const deleteProductModel = async (
  id: string,
  options?: RequestInit
): Promise<deleteProductModelResponse> => {
  return customInstance<deleteProductModelResponse>(
    getDeleteProductModelUrl(id),
    {
      ...options,
      method: 'DELETE'
    }
  )
}

export const getDeleteProductModelMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProductModel>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProductModel>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteProductModel']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProductModel>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteProductModel(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteProductModelMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProductModel>>
>

export type DeleteProductModelMutationError = ErrorType<void>

/**
 * @summary Delete a product model
 */
export const useDeleteProductModel = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteProductModel>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteProductModel>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteProductModelMutationOptions(options), queryClient)
}
