/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { Batch, CreateBatchDto, GetBatchDto } from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get all batches
 */
export type getAllBatchesResponse200 = {
  data: GetBatchDto[]
  status: 200
}

export type getAllBatchesResponse401 = {
  data: void
  status: 401
}

export type getAllBatchesResponse403 = {
  data: void
  status: 403
}

export type getAllBatchesResponseSuccess = getAllBatchesResponse200 & {
  headers: Headers
}
export type getAllBatchesResponseError = (
  | getAllBatchesResponse401
  | getAllBatchesResponse403
) & {
  headers: Headers
}

export type getAllBatchesResponse =
  | getAllBatchesResponseSuccess
  | getAllBatchesResponseError

export const getGetAllBatchesUrl = () => {
  return `/batches`
}

export const getAllBatches = async (
  options?: RequestInit
): Promise<getAllBatchesResponse> => {
  return customInstance<getAllBatchesResponse>(getGetAllBatchesUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllBatchesQueryKey = () => {
  return [`/batches`] as const
}

export const getGetAllBatchesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllBatches>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllBatches>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllBatchesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBatches>>> = ({
    signal
  }) => getAllBatches({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllBatches>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllBatchesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllBatches>>
>
export type GetAllBatchesQueryError = ErrorType<void>

export function useGetAllBatches<
  TData = Awaited<ReturnType<typeof getAllBatches>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBatches>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBatches>>,
          TError,
          Awaited<ReturnType<typeof getAllBatches>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllBatches<
  TData = Awaited<ReturnType<typeof getAllBatches>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBatches>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBatches>>,
          TError,
          Awaited<ReturnType<typeof getAllBatches>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllBatches<
  TData = Awaited<ReturnType<typeof getAllBatches>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBatches>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all batches
 */

export function useGetAllBatches<
  TData = Awaited<ReturnType<typeof getAllBatches>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBatches>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllBatchesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Create a new batch
 */
export type createBatchResponse201 = {
  data: Batch
  status: 201
}

export type createBatchResponse401 = {
  data: void
  status: 401
}

export type createBatchResponse403 = {
  data: void
  status: 403
}

export type createBatchResponseSuccess = createBatchResponse201 & {
  headers: Headers
}
export type createBatchResponseError = (
  | createBatchResponse401
  | createBatchResponse403
) & {
  headers: Headers
}

export type createBatchResponse =
  | createBatchResponseSuccess
  | createBatchResponseError

export const getCreateBatchUrl = () => {
  return `/batches`
}

export const createBatch = async (
  createBatchDto: CreateBatchDto,
  options?: RequestInit
): Promise<createBatchResponse> => {
  return customInstance<createBatchResponse>(getCreateBatchUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBatchDto)
  })
}

export const getCreateBatchMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBatch>>,
    TError,
    { data: CreateBatchDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBatch>>,
  TError,
  { data: CreateBatchDto },
  TContext
> => {
  const mutationKey = ['createBatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBatch>>,
    { data: CreateBatchDto }
  > = (props) => {
    const { data } = props ?? {}

    return createBatch(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateBatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBatch>>
>
export type CreateBatchMutationBody = CreateBatchDto
export type CreateBatchMutationError = ErrorType<void>

/**
 * @summary Create a new batch
 */
export const useCreateBatch = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createBatch>>,
      TError,
      { data: CreateBatchDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createBatch>>,
  TError,
  { data: CreateBatchDto },
  TContext
> => {
  return useMutation(getCreateBatchMutationOptions(options), queryClient)
}
/**
 * @summary Get a specific batch
 */
export type getOneBatchResponse200 = {
  data: GetBatchDto
  status: 200
}

export type getOneBatchResponse401 = {
  data: void
  status: 401
}

export type getOneBatchResponse403 = {
  data: void
  status: 403
}

export type getOneBatchResponse404 = {
  data: void
  status: 404
}

export type getOneBatchResponseSuccess = getOneBatchResponse200 & {
  headers: Headers
}
export type getOneBatchResponseError = (
  | getOneBatchResponse401
  | getOneBatchResponse403
  | getOneBatchResponse404
) & {
  headers: Headers
}

export type getOneBatchResponse =
  | getOneBatchResponseSuccess
  | getOneBatchResponseError

export const getGetOneBatchUrl = (id: string) => {
  return `/batches/${id}`
}

export const getOneBatch = async (
  id: string,
  options?: RequestInit
): Promise<getOneBatchResponse> => {
  return customInstance<getOneBatchResponse>(getGetOneBatchUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneBatchQueryKey = (id: string) => {
  return [`/batches/${id}`] as const
}

export const getGetOneBatchQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneBatch>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneBatch>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneBatchQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneBatch>>> = ({
    signal
  }) => getOneBatch(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneBatch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneBatchQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneBatch>>
>
export type GetOneBatchQueryError = ErrorType<void>

export function useGetOneBatch<
  TData = Awaited<ReturnType<typeof getOneBatch>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneBatch>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneBatch>>,
          TError,
          Awaited<ReturnType<typeof getOneBatch>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneBatch<
  TData = Awaited<ReturnType<typeof getOneBatch>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneBatch>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneBatch>>,
          TError,
          Awaited<ReturnType<typeof getOneBatch>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneBatch<
  TData = Awaited<ReturnType<typeof getOneBatch>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneBatch>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific batch
 */

export function useGetOneBatch<
  TData = Awaited<ReturnType<typeof getOneBatch>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneBatch>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneBatchQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Delete a batch
 */
export type deleteBatchResponse204 = {
  data: void
  status: 204
}

export type deleteBatchResponse401 = {
  data: void
  status: 401
}

export type deleteBatchResponse403 = {
  data: void
  status: 403
}

export type deleteBatchResponseSuccess = deleteBatchResponse204 & {
  headers: Headers
}
export type deleteBatchResponseError = (
  | deleteBatchResponse401
  | deleteBatchResponse403
) & {
  headers: Headers
}

export type deleteBatchResponse =
  | deleteBatchResponseSuccess
  | deleteBatchResponseError

export const getDeleteBatchUrl = (id: string) => {
  return `/batches/${id}`
}

export const deleteBatch = async (
  id: string,
  options?: RequestInit
): Promise<deleteBatchResponse> => {
  return customInstance<deleteBatchResponse>(getDeleteBatchUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

export const getDeleteBatchMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBatch>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBatch>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteBatch']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBatch>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteBatch(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteBatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBatch>>
>

export type DeleteBatchMutationError = ErrorType<void>

/**
 * @summary Delete a batch
 */
export const useDeleteBatch = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteBatch>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteBatch>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteBatchMutationOptions(options), queryClient)
}
