/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { CreateSupplierDto, Supplier, UpdateSupplierDto } from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Create a new supplier
 */
export type createSupplierResponse201 = {
  data: Supplier
  status: 201
}

export type createSupplierResponse401 = {
  data: void
  status: 401
}

export type createSupplierResponse403 = {
  data: void
  status: 403
}

export type createSupplierResponseSuccess = createSupplierResponse201 & {
  headers: Headers
}
export type createSupplierResponseError = (
  | createSupplierResponse401
  | createSupplierResponse403
) & {
  headers: Headers
}

export type createSupplierResponse =
  | createSupplierResponseSuccess
  | createSupplierResponseError

export const getCreateSupplierUrl = () => {
  return `/suppliers`
}

export const createSupplier = async (
  createSupplierDto: CreateSupplierDto,
  options?: RequestInit
): Promise<createSupplierResponse> => {
  return customInstance<createSupplierResponse>(getCreateSupplierUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSupplierDto)
  })
}

export const getCreateSupplierMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSupplier>>,
    TError,
    { data: CreateSupplierDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSupplier>>,
  TError,
  { data: CreateSupplierDto },
  TContext
> => {
  const mutationKey = ['createSupplier']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSupplier>>,
    { data: CreateSupplierDto }
  > = (props) => {
    const { data } = props ?? {}

    return createSupplier(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateSupplierMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSupplier>>
>
export type CreateSupplierMutationBody = CreateSupplierDto
export type CreateSupplierMutationError = ErrorType<void>

/**
 * @summary Create a new supplier
 */
export const useCreateSupplier = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSupplier>>,
      TError,
      { data: CreateSupplierDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createSupplier>>,
  TError,
  { data: CreateSupplierDto },
  TContext
> => {
  return useMutation(getCreateSupplierMutationOptions(options), queryClient)
}
/**
 * @summary Get all suppliers
 */
export type getAllSuppliersResponse200 = {
  data: Supplier[]
  status: 200
}

export type getAllSuppliersResponse401 = {
  data: void
  status: 401
}

export type getAllSuppliersResponse403 = {
  data: void
  status: 403
}

export type getAllSuppliersResponseSuccess = getAllSuppliersResponse200 & {
  headers: Headers
}
export type getAllSuppliersResponseError = (
  | getAllSuppliersResponse401
  | getAllSuppliersResponse403
) & {
  headers: Headers
}

export type getAllSuppliersResponse =
  | getAllSuppliersResponseSuccess
  | getAllSuppliersResponseError

export const getGetAllSuppliersUrl = () => {
  return `/suppliers`
}

export const getAllSuppliers = async (
  options?: RequestInit
): Promise<getAllSuppliersResponse> => {
  return customInstance<getAllSuppliersResponse>(getGetAllSuppliersUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllSuppliersQueryKey = () => {
  return [`/suppliers`] as const
}

export const getGetAllSuppliersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllSuppliers>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllSuppliers>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllSuppliersQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSuppliers>>> = ({
    signal
  }) => getAllSuppliers({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllSuppliers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllSuppliersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllSuppliers>>
>
export type GetAllSuppliersQueryError = ErrorType<void>

export function useGetAllSuppliers<
  TData = Awaited<ReturnType<typeof getAllSuppliers>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSuppliers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSuppliers>>,
          TError,
          Awaited<ReturnType<typeof getAllSuppliers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllSuppliers<
  TData = Awaited<ReturnType<typeof getAllSuppliers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSuppliers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSuppliers>>,
          TError,
          Awaited<ReturnType<typeof getAllSuppliers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllSuppliers<
  TData = Awaited<ReturnType<typeof getAllSuppliers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSuppliers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all suppliers
 */

export function useGetAllSuppliers<
  TData = Awaited<ReturnType<typeof getAllSuppliers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllSuppliers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllSuppliersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a specific supplier
 */
export type getOneSupplierResponse200 = {
  data: Supplier
  status: 200
}

export type getOneSupplierResponse401 = {
  data: void
  status: 401
}

export type getOneSupplierResponse403 = {
  data: void
  status: 403
}

export type getOneSupplierResponse404 = {
  data: void
  status: 404
}

export type getOneSupplierResponseSuccess = getOneSupplierResponse200 & {
  headers: Headers
}
export type getOneSupplierResponseError = (
  | getOneSupplierResponse401
  | getOneSupplierResponse403
  | getOneSupplierResponse404
) & {
  headers: Headers
}

export type getOneSupplierResponse =
  | getOneSupplierResponseSuccess
  | getOneSupplierResponseError

export const getGetOneSupplierUrl = (id: string) => {
  return `/suppliers/${id}`
}

export const getOneSupplier = async (
  id: string,
  options?: RequestInit
): Promise<getOneSupplierResponse> => {
  return customInstance<getOneSupplierResponse>(getGetOneSupplierUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneSupplierQueryKey = (id: string) => {
  return [`/suppliers/${id}`] as const
}

export const getGetOneSupplierQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneSupplier>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSupplier>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneSupplierQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneSupplier>>> = ({
    signal
  }) => getOneSupplier(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneSupplier>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneSupplierQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneSupplier>>
>
export type GetOneSupplierQueryError = ErrorType<void>

export function useGetOneSupplier<
  TData = Awaited<ReturnType<typeof getOneSupplier>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSupplier>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneSupplier>>,
          TError,
          Awaited<ReturnType<typeof getOneSupplier>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneSupplier<
  TData = Awaited<ReturnType<typeof getOneSupplier>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSupplier>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneSupplier>>,
          TError,
          Awaited<ReturnType<typeof getOneSupplier>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneSupplier<
  TData = Awaited<ReturnType<typeof getOneSupplier>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSupplier>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific supplier
 */

export function useGetOneSupplier<
  TData = Awaited<ReturnType<typeof getOneSupplier>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSupplier>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneSupplierQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a supplier
 */
export type updateSupplierResponse200 = {
  data: Supplier
  status: 200
}

export type updateSupplierResponse401 = {
  data: void
  status: 401
}

export type updateSupplierResponse403 = {
  data: void
  status: 403
}

export type updateSupplierResponseSuccess = updateSupplierResponse200 & {
  headers: Headers
}
export type updateSupplierResponseError = (
  | updateSupplierResponse401
  | updateSupplierResponse403
) & {
  headers: Headers
}

export type updateSupplierResponse =
  | updateSupplierResponseSuccess
  | updateSupplierResponseError

export const getUpdateSupplierUrl = (id: string) => {
  return `/suppliers/${id}`
}

export const updateSupplier = async (
  id: string,
  updateSupplierDto: UpdateSupplierDto,
  options?: RequestInit
): Promise<updateSupplierResponse> => {
  return customInstance<updateSupplierResponse>(getUpdateSupplierUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSupplierDto)
  })
}

export const getUpdateSupplierMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSupplier>>,
    TError,
    { id: string; data: UpdateSupplierDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSupplier>>,
  TError,
  { id: string; data: UpdateSupplierDto },
  TContext
> => {
  const mutationKey = ['updateSupplier']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSupplier>>,
    { id: string; data: UpdateSupplierDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateSupplier(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateSupplierMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSupplier>>
>
export type UpdateSupplierMutationBody = UpdateSupplierDto
export type UpdateSupplierMutationError = ErrorType<void>

/**
 * @summary Update a supplier
 */
export const useUpdateSupplier = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSupplier>>,
      TError,
      { id: string; data: UpdateSupplierDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateSupplier>>,
  TError,
  { id: string; data: UpdateSupplierDto },
  TContext
> => {
  return useMutation(getUpdateSupplierMutationOptions(options), queryClient)
}
/**
 * @summary Delete a supplier
 */
export type deleteSupplierResponse204 = {
  data: void
  status: 204
}

export type deleteSupplierResponse401 = {
  data: void
  status: 401
}

export type deleteSupplierResponse403 = {
  data: void
  status: 403
}

export type deleteSupplierResponseSuccess = deleteSupplierResponse204 & {
  headers: Headers
}
export type deleteSupplierResponseError = (
  | deleteSupplierResponse401
  | deleteSupplierResponse403
) & {
  headers: Headers
}

export type deleteSupplierResponse =
  | deleteSupplierResponseSuccess
  | deleteSupplierResponseError

export const getDeleteSupplierUrl = (id: string) => {
  return `/suppliers/${id}`
}

export const deleteSupplier = async (
  id: string,
  options?: RequestInit
): Promise<deleteSupplierResponse> => {
  return customInstance<deleteSupplierResponse>(getDeleteSupplierUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

export const getDeleteSupplierMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSupplier>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSupplier>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteSupplier']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSupplier>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteSupplier(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteSupplierMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteSupplier>>
>

export type DeleteSupplierMutationError = ErrorType<void>

/**
 * @summary Delete a supplier
 */
export const useDeleteSupplier = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSupplier>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSupplier>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteSupplierMutationOptions(options), queryClient)
}
