/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  CreateShipmentDto,
  GetShipmentDto,
  Shipment,
  UpdateShipmentDto,
  UpdateStatusShipmentDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get all shipments
 */
export type getAllShipmentsResponse200 = {
  data: GetShipmentDto[]
  status: 200
}

export type getAllShipmentsResponse401 = {
  data: void
  status: 401
}

export type getAllShipmentsResponse403 = {
  data: void
  status: 403
}

export type getAllShipmentsResponseSuccess = getAllShipmentsResponse200 & {
  headers: Headers
}
export type getAllShipmentsResponseError = (
  | getAllShipmentsResponse401
  | getAllShipmentsResponse403
) & {
  headers: Headers
}

export type getAllShipmentsResponse =
  | getAllShipmentsResponseSuccess
  | getAllShipmentsResponseError

export const getGetAllShipmentsUrl = () => {
  return `/shipments`
}

export const getAllShipments = async (
  options?: RequestInit
): Promise<getAllShipmentsResponse> => {
  return customInstance<getAllShipmentsResponse>(getGetAllShipmentsUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllShipmentsQueryKey = () => {
  return [`/shipments`] as const
}

export const getGetAllShipmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllShipments>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllShipments>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllShipmentsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllShipments>>> = ({
    signal
  }) => getAllShipments({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllShipments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllShipmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllShipments>>
>
export type GetAllShipmentsQueryError = ErrorType<void>

export function useGetAllShipments<
  TData = Awaited<ReturnType<typeof getAllShipments>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllShipments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllShipments>>,
          TError,
          Awaited<ReturnType<typeof getAllShipments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllShipments<
  TData = Awaited<ReturnType<typeof getAllShipments>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllShipments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllShipments>>,
          TError,
          Awaited<ReturnType<typeof getAllShipments>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllShipments<
  TData = Awaited<ReturnType<typeof getAllShipments>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllShipments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all shipments
 */

export function useGetAllShipments<
  TData = Awaited<ReturnType<typeof getAllShipments>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllShipments>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllShipmentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Create a new shipment
 */
export type createShipmentResponse201 = {
  data: Shipment
  status: 201
}

export type createShipmentResponse401 = {
  data: void
  status: 401
}

export type createShipmentResponse403 = {
  data: void
  status: 403
}

export type createShipmentResponseSuccess = createShipmentResponse201 & {
  headers: Headers
}
export type createShipmentResponseError = (
  | createShipmentResponse401
  | createShipmentResponse403
) & {
  headers: Headers
}

export type createShipmentResponse =
  | createShipmentResponseSuccess
  | createShipmentResponseError

export const getCreateShipmentUrl = () => {
  return `/shipments`
}

export const createShipment = async (
  createShipmentDto: CreateShipmentDto,
  options?: RequestInit
): Promise<createShipmentResponse> => {
  return customInstance<createShipmentResponse>(getCreateShipmentUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createShipmentDto)
  })
}

export const getCreateShipmentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createShipment>>,
    TError,
    { data: CreateShipmentDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createShipment>>,
  TError,
  { data: CreateShipmentDto },
  TContext
> => {
  const mutationKey = ['createShipment']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createShipment>>,
    { data: CreateShipmentDto }
  > = (props) => {
    const { data } = props ?? {}

    return createShipment(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateShipmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createShipment>>
>
export type CreateShipmentMutationBody = CreateShipmentDto
export type CreateShipmentMutationError = ErrorType<void>

/**
 * @summary Create a new shipment
 */
export const useCreateShipment = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createShipment>>,
      TError,
      { data: CreateShipmentDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createShipment>>,
  TError,
  { data: CreateShipmentDto },
  TContext
> => {
  return useMutation(getCreateShipmentMutationOptions(options), queryClient)
}
/**
 * @summary Get a specific shipment
 */
export type getOneShipmentResponse200 = {
  data: GetShipmentDto
  status: 200
}

export type getOneShipmentResponse401 = {
  data: void
  status: 401
}

export type getOneShipmentResponse403 = {
  data: void
  status: 403
}

export type getOneShipmentResponse404 = {
  data: void
  status: 404
}

export type getOneShipmentResponseSuccess = getOneShipmentResponse200 & {
  headers: Headers
}
export type getOneShipmentResponseError = (
  | getOneShipmentResponse401
  | getOneShipmentResponse403
  | getOneShipmentResponse404
) & {
  headers: Headers
}

export type getOneShipmentResponse =
  | getOneShipmentResponseSuccess
  | getOneShipmentResponseError

export const getGetOneShipmentUrl = (id: string) => {
  return `/shipments/${id}`
}

export const getOneShipment = async (
  id: string,
  options?: RequestInit
): Promise<getOneShipmentResponse> => {
  return customInstance<getOneShipmentResponse>(getGetOneShipmentUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneShipmentQueryKey = (id: string) => {
  return [`/shipments/${id}`] as const
}

export const getGetOneShipmentQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneShipment>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneShipment>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneShipmentQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneShipment>>> = ({
    signal
  }) => getOneShipment(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneShipment>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneShipmentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneShipment>>
>
export type GetOneShipmentQueryError = ErrorType<void>

export function useGetOneShipment<
  TData = Awaited<ReturnType<typeof getOneShipment>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneShipment>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneShipment>>,
          TError,
          Awaited<ReturnType<typeof getOneShipment>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneShipment<
  TData = Awaited<ReturnType<typeof getOneShipment>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneShipment>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneShipment>>,
          TError,
          Awaited<ReturnType<typeof getOneShipment>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneShipment<
  TData = Awaited<ReturnType<typeof getOneShipment>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneShipment>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific shipment
 */

export function useGetOneShipment<
  TData = Awaited<ReturnType<typeof getOneShipment>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneShipment>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneShipmentQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a shipment
 */
export type updateShipmentResponse200 = {
  data: Shipment
  status: 200
}

export type updateShipmentResponse401 = {
  data: void
  status: 401
}

export type updateShipmentResponse403 = {
  data: void
  status: 403
}

export type updateShipmentResponseSuccess = updateShipmentResponse200 & {
  headers: Headers
}
export type updateShipmentResponseError = (
  | updateShipmentResponse401
  | updateShipmentResponse403
) & {
  headers: Headers
}

export type updateShipmentResponse =
  | updateShipmentResponseSuccess
  | updateShipmentResponseError

export const getUpdateShipmentUrl = (id: string) => {
  return `/shipments/${id}`
}

export const updateShipment = async (
  id: string,
  updateShipmentDto: UpdateShipmentDto,
  options?: RequestInit
): Promise<updateShipmentResponse> => {
  return customInstance<updateShipmentResponse>(getUpdateShipmentUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateShipmentDto)
  })
}

export const getUpdateShipmentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateShipment>>,
    TError,
    { id: string; data: UpdateShipmentDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateShipment>>,
  TError,
  { id: string; data: UpdateShipmentDto },
  TContext
> => {
  const mutationKey = ['updateShipment']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateShipment>>,
    { id: string; data: UpdateShipmentDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateShipment(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateShipmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateShipment>>
>
export type UpdateShipmentMutationBody = UpdateShipmentDto
export type UpdateShipmentMutationError = ErrorType<void>

/**
 * @summary Update a shipment
 */
export const useUpdateShipment = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateShipment>>,
      TError,
      { id: string; data: UpdateShipmentDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateShipment>>,
  TError,
  { id: string; data: UpdateShipmentDto },
  TContext
> => {
  return useMutation(getUpdateShipmentMutationOptions(options), queryClient)
}
/**
 * @summary Delete a shipment
 */
export type deleteShipmentResponse204 = {
  data: void
  status: 204
}

export type deleteShipmentResponse401 = {
  data: void
  status: 401
}

export type deleteShipmentResponse403 = {
  data: void
  status: 403
}

export type deleteShipmentResponseSuccess = deleteShipmentResponse204 & {
  headers: Headers
}
export type deleteShipmentResponseError = (
  | deleteShipmentResponse401
  | deleteShipmentResponse403
) & {
  headers: Headers
}

export type deleteShipmentResponse =
  | deleteShipmentResponseSuccess
  | deleteShipmentResponseError

export const getDeleteShipmentUrl = (id: string) => {
  return `/shipments/${id}`
}

export const deleteShipment = async (
  id: string,
  options?: RequestInit
): Promise<deleteShipmentResponse> => {
  return customInstance<deleteShipmentResponse>(getDeleteShipmentUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

export const getDeleteShipmentMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteShipment>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteShipment>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteShipment']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteShipment>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteShipment(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteShipmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteShipment>>
>

export type DeleteShipmentMutationError = ErrorType<void>

/**
 * @summary Delete a shipment
 */
export const useDeleteShipment = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteShipment>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteShipment>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteShipmentMutationOptions(options), queryClient)
}
/**
 * @summary Update the status of a shipment
 */
export type updateShipmentStatusResponse200 = {
  data: Shipment
  status: 200
}

export type updateShipmentStatusResponse401 = {
  data: void
  status: 401
}

export type updateShipmentStatusResponse403 = {
  data: void
  status: 403
}

export type updateShipmentStatusResponseSuccess =
  updateShipmentStatusResponse200 & {
    headers: Headers
  }
export type updateShipmentStatusResponseError = (
  | updateShipmentStatusResponse401
  | updateShipmentStatusResponse403
) & {
  headers: Headers
}

export type updateShipmentStatusResponse =
  | updateShipmentStatusResponseSuccess
  | updateShipmentStatusResponseError

export const getUpdateShipmentStatusUrl = (id: string) => {
  return `/shipments/${id}/status`
}

export const updateShipmentStatus = async (
  id: string,
  updateStatusShipmentDto: UpdateStatusShipmentDto,
  options?: RequestInit
): Promise<updateShipmentStatusResponse> => {
  return customInstance<updateShipmentStatusResponse>(
    getUpdateShipmentStatusUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateStatusShipmentDto)
    }
  )
}

export const getUpdateShipmentStatusMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateShipmentStatus>>,
    TError,
    { id: string; data: UpdateStatusShipmentDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateShipmentStatus>>,
  TError,
  { id: string; data: UpdateStatusShipmentDto },
  TContext
> => {
  const mutationKey = ['updateShipmentStatus']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateShipmentStatus>>,
    { id: string; data: UpdateStatusShipmentDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateShipmentStatus(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateShipmentStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateShipmentStatus>>
>
export type UpdateShipmentStatusMutationBody = UpdateStatusShipmentDto
export type UpdateShipmentStatusMutationError = ErrorType<void>

/**
 * @summary Update the status of a shipment
 */
export const useUpdateShipmentStatus = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateShipmentStatus>>,
      TError,
      { id: string; data: UpdateStatusShipmentDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateShipmentStatus>>,
  TError,
  { id: string; data: UpdateStatusShipmentDto },
  TContext
> => {
  return useMutation(
    getUpdateShipmentStatusMutationOptions(options),
    queryClient
  )
}
