/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { AddressCountry } from './addressCountry'
import type { AddressFederativeUnit } from './addressFederativeUnit'
import type { PostalCode } from './postalCode'

export interface Address {
  /** The street of the address */
  street: string
  /** The number of the address */
  number: number
  /** The neighborhood of the address */
  neighborhood: string
  /** The city of the address */
  city: string
  /** The federative unit of the address */
  federativeUnit: AddressFederativeUnit
  /** The postal code of the address */
  postalCode: PostalCode
  /** The country of the address */
  country: AddressCountry
  /** The complement of the address */
  complement: string
}
