/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The country of the address
 */
export type AddressCountry =
  (typeof AddressCountry)[keyof typeof AddressCountry]

export const AddressCountry = {
  Brasil: 'Brasil'
} as const
