/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface Batch {
  /** The ID of the batch */
  id: string
  /** The arrival date of the batch */
  arrivalDate: string
  /** The ID of the supplier */
  supplierId: string
}
