/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { CategoryName } from './categoryName'
import type { CategoryStatus } from './categoryStatus'
import type { Description } from './description'

export interface Category {
  /** The ID of the category */
  id: string
  /** The name of the category */
  name: CategoryName
  /** The description of the category */
  description?: Description
  /** The status of the category */
  status: CategoryStatus
}
