/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface ChangePasswordDto {
  /**
   * New password (must contain at least 10 characters, one uppercase, one lowercase, one number and one special character)
   * @minLength 10
   */
  newPassword: string
}
