/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * Country
 */
export type Country = (typeof Country)[keyof typeof Country]

export const Country = {
  Brasil: 'Brasil'
} as const
