/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { ProductEntryDto } from './productEntryDto'

export interface CreateBatchDto {
  /** The arrival date of the batch */
  arrivalDate: string
  /** The ID of the supplier */
  supplierId: string
  /** The items of the batch */
  entries: ProductEntryDto[]
}
