/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface CreateShipmentDto {
  /** The ID of the reseller */
  resellerId: string
  /** The IDs of the products */
  productIds: string[]
}
