/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface CreateReturnDto {
  /** The ID of the reseller */
  resellerId?: string
  /** The IDs of the items */
  items?: string[]
}
