/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface CreateProductModelDto {
  /** The name of the product model */
  name: string
  /** The ID of the category */
  categoryId: string
  /** The suggested price of the product model */
  suggestedPrice: string
  /** The description of the product model */
  description?: string
  /** Photo of the product model */
  photo?: Blob
}
