/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { PaymentMethod } from './paymentMethod'

export interface CreateSaleDto {
  /** The IDs of the products */
  productIds: string[]
  /** The date of the sale */
  saleDate: string
  /** The payment method of the sale */
  paymentMethod: PaymentMethod
  /** The number of installments of the sale */
  numberInstallments: number
  /** The interval of installments of the sale */
  installmentsInterval: number
  /** The ID of the consumer */
  customerId: string
}
