/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface Description {
  /**
   * The description of the product model
   * @maxLength 500
   */
  value: string
}
