/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { GetAllReturnDtoStatus } from './getAllReturnDtoStatus'
import type { ReturnProductDto } from './returnProductDto'

export interface GetAllReturnDto {
  /** The ID of the return */
  id: string
  /** The ID of the reseller */
  resellerId: string
  /** The name of the reseller */
  resellerName: string
  /** The IDs of the products being returned */
  products: ReturnProductDto[]
  /** The status of the return */
  status: GetAllReturnDtoStatus
  /** The creation date of the return */
  createdAt: string
}
