/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { GetSaleProductDto } from './getSaleProductDto'
import type { ImageURL } from './imageURL'
import type { ModelName } from './modelName'

export interface GetAvailableProductModelDto {
  /** The ID of the product model */
  id: string
  /** The name of the product model */
  modelName: ModelName
  /** The image URL of the product model */
  imageUrl?: ImageURL
  /** The available products for the model */
  products: GetSaleProductDto[]
}
