/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Currency } from './currency'
import type { GetBatchProductDto } from './getBatchProductDto'

export interface GetBatchDto {
  /** The arrival date of the batch */
  arrivalDate: string
  /** The supplier ID of the batch */
  supplierId: string
  /** The ID of the batch */
  id: string
  /** The supplier name of the batch */
  supplierName: string
  /** The total number of items in the batch */
  totalItems: number
  /** The total cost of the batch */
  totalCost: Currency
  /** The items in the batch */
  items: GetBatchProductDto[]
}
