/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Product } from './product'
import type { ProductModel } from './productModel'

export interface GetInventoryByIdReturnDto {
  /** The ID of the reseller */
  resellerId: string
  /** The full name of the reseller */
  resellerName: string
  /** The products in the inventory */
  products: Product[]
  /** The Product Models associated with the products in the inventory */
  productModels: ProductModel[]
}
