/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { CategoryName } from './categoryName'
import type { Currency } from './currency'
import type { ModelName } from './modelName'
import type { SerialNumber } from './serialNumber'

export interface GetSaleProductDto {
  /** The ID of the sale product */
  id: string
  /** The serial number of the product */
  serialNumber: SerialNumber
  /** The sale price of the product */
  salePrice: Currency
  /** The name of the product model */
  modelName: ModelName
  /** The name of the category */
  categoryName: CategoryName
  /** The ID of the product model */
  modelId: string
  /** The ID of the category */
  categoryId: string
}
