/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Currency } from './currency'
import type { GetSaleDtoPaymentMethod } from './getSaleDtoPaymentMethod'
import type { GetSaleDtoStatus } from './getSaleDtoStatus'
import type { GetSaleProductDto } from './getSaleProductDto'
import type { Name } from './name'
import type { PhoneNumber } from './phoneNumber'
import type { Unit } from './unit'

export interface GetSaleDto {
  /** The ID of the sale */
  id: string
  /** The ID of the customer */
  customerId: string
  /** The name of the customer */
  customerName: Name
  /** The phone number of the customer */
  customerPhone: PhoneNumber
  /** The ID of the reseller */
  resellerId: string
  /** The name of the reseller */
  resellerName: string
  /** The products in the sale */
  products: GetSaleProductDto[]
  /** The date of the sale */
  saleDate: string
  /** The total amount of the sale */
  totalAmount: Currency
  /** The payment method of the sale */
  paymentMethod: GetSaleDtoPaymentMethod
  /** The number of installments */
  numberInstallments: Unit
  /** The status of the sale */
  status: GetSaleDtoStatus
  /** The interval between installments in days */
  installmentsInterval: Unit
  /** The number of installments paid */
  installmentsPaid: Unit
}
