/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export type GetTotalProductsWithResellersParams = {
  start?: string
  end?: string
  limit?: number
  page?: number
}
