/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** The email of the user */
  email: string
  /** The password of the user. Must contain at least 10 characters, one uppercase letter, one lowercase letter, one number and one special character */
  password: string
}
