/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface MonthlySalesDto {
  /** Month number (1-12) */
  month: number
  /** Number of sales */
  countSales: number
  /** Total sales amount */
  totalAmount: string
  /** Year of sales */
  year?: number
}
