/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { OwnershipTransferStatusProperty } from './ownershipTransferStatusProperty'

export interface OwnershipTransfer {
  /** The ID of the ownership transfer */
  id: string
  /** The ID of the product */
  productId: string
  /** The ID of the from reseller */
  fromResellerId: string
  /** The ID of the to reseller */
  toResellerId: string
  /** The transfer date */
  transferDate: string
  /** The status of the ownership transfer */
  status: OwnershipTransferStatusProperty
}
