/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the ownership transfer
 */
export type OwnershipTransferStatusProperty =
  (typeof OwnershipTransferStatusProperty)[keyof typeof OwnershipTransferStatusProperty]

export const OwnershipTransferStatusProperty = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED'
} as const
