/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The new status of the ownership transfer
 */
export type OwnershipTransferStatus =
  (typeof OwnershipTransferStatus)[keyof typeof OwnershipTransferStatus]

export const OwnershipTransferStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED'
} as const
