/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export type PasswordResetRequestResponseDtoStatus =
  (typeof PasswordResetRequestResponseDtoStatus)[keyof typeof PasswordResetRequestResponseDtoStatus]

export const PasswordResetRequestResponseDtoStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
} as const
