/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Email } from './email'
import type { PasswordResetRequestResponseDtoStatus } from './passwordResetRequestResponseDtoStatus'
import type { PasswordResetRequestResponseDtoUser } from './passwordResetRequestResponseDtoUser'
import type { PhoneNumber } from './phoneNumber'

export interface PasswordResetRequestResponseDto {
  id: string
  userId: string
  username: string
  email: Email
  phone: PhoneNumber
  token: string
  status: PasswordResetRequestResponseDtoStatus
  createdAt: string
  approvedAt?: string
  rejectedAt?: string
  completedAt?: string
  user?: PasswordResetRequestResponseDtoUser
}
