/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the product model
 */
export type ProductModelStatus =
  (typeof ProductModelStatus)[keyof typeof ProductModelStatus]

export const ProductModelStatus = {
  USED: 'USED',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED'
} as const
