/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface ProductEntryDto {
  /** The unique identifier of the product model */
  modelId?: string
  /** The name of the product model */
  modelName?: string
  /** The unique identifier of the product category */
  categoryId?: string
  /** The quantity of the product */
  quantity: number
  /** The unit cost of the product */
  unitCost: string
  /** The sale price of the product */
  salePrice: string
  /** The URL of the product image */
  photoUrl?: string
}
