/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the product
 */
export type ProductStatus = (typeof ProductStatus)[keyof typeof ProductStatus]

export const ProductStatus = {
  IN_STOCK: 'IN_STOCK',
  ASSIGNED: 'ASSIGNED',
  SOLD: 'SOLD'
} as const
