/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface ProductInInventoryDto {
  /** The ID of the product */
  id: string
  /** The serial number of the product */
  serialNumber: string
  /** The ID of the product model */
  modelId: string
  /** The name of the product model */
  modelName: string
  /** The sale price of the product */
  salePrice: string
  /** The date when the product was acquired (batch arrival date) */
  dateAcquired: string
}
