/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Currency } from './currency'
import type { ProductStatus } from './productStatus'
import type { SerialNumber } from './serialNumber'

export interface Product {
  /** The ID of the product */
  id: string
  /** The serial number of the product */
  serialNumber: SerialNumber
  /** The ID of the product model */
  modelId: string
  /** The ID of the batch */
  batchId: string
  /** The unit cost of the product */
  unitCost: Currency
  /** The sale price of the product */
  salePrice: Currency
  /** The status of the product */
  status: ProductStatus
}
