/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Currency } from './currency'
import type { Description } from './description'
import type { ImageURL } from './imageURL'
import type { ModelName } from './modelName'
import type { ProductModelStatus } from './productModelStatus'

export interface ProductModel {
  /** The ID of the product model */
  id: string
  /** The name of the product model */
  name: ModelName
  /** The ID of the category */
  categoryId: string
  /** The suggested price of the product model */
  suggestedPrice: Currency
  /** The description of the product model */
  description?: Description
  /** The URL of the product model photo */
  photoUrl?: ImageURL
  /** The status of the product model */
  status: ProductModelStatus
}
