/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface ReturnProduct {
  /** The ID of the return product */
  productId: string
  /** The name of the product */
  productModelId: string
  /** The name of the product model */
  productModelName: string
  /** The serial number of the product */
  serialNumber: string
}
