/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the return
 */
export type ReturnStatus = (typeof ReturnStatus)[keyof typeof ReturnStatus]

export const ReturnStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  RETURNED: 'RETURNED',
  CANCELLED: 'CANCELLED'
} as const
