/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { ModelName } from './modelName'
import type { SerialNumber } from './serialNumber'

export interface ReturnProductDto {
  /** The ID of the product being returned */
  productId: string
  /** The reason for the return */
  productModelName: ModelName
  /** The serial number of the product being returned */
  serialNumber: SerialNumber
}
