/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { ReturnStatus } from './returnStatus'

export interface Return {
  /** The ID of the return */
  id: string
  /** The ID of the reseller */
  resellerId: string
  /** The IDs of the products being returned */
  productIds: string[]
  /** The status of the return */
  status: ReturnStatus
  /** The creation date of the return */
  createdAt: string
}
