/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { ReturnProduct } from './returnProduct'

export interface ReturnWithResellerDto {
  /** The ID of the return */
  id: string
  /** The ID of the reseller */
  resellerId: string
  /** The name of the reseller */
  resellerName: string
  /** The products in the return */
  products: ReturnProduct[]
}
