/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Currency } from './currency'
import type { SalePaymentMethod } from './salePaymentMethod'
import type { SaleStatus } from './saleStatus'
import type { Unit } from './unit'

export interface Sale {
  /** The ID of the sale */
  id: string
  /** The ID of the consumer */
  customerId: string
  /** The ID of the reseller */
  resellerId: string
  /** The IDs of the products in the sale */
  productIds: string[]
  /** The date of the sale */
  saleDate: string
  /** The total amount of the sale */
  totalAmount: Currency
  /** The payment method of the sale */
  paymentMethod: SalePaymentMethod
  /** The number of installments */
  numberInstallments: Unit
  /** The status of the sale */
  status: SaleStatus
  /** The interval between installments in days */
  installmentsInterval: Unit
  /** The number of installments paid */
  installmentsPaid: Unit
}
