/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { SaleByResellerReturnDto } from './saleByResellerReturnDto'

export interface SalesByResellerDto {
  /** The ID of the reseller */
  resellerId: string
  /** The name of the reseller */
  resellerName: string
  /** The sales made by the reseller */
  sales: SaleByResellerReturnDto[]
  /** The total sales amount made by the reseller */
  totalSales: string
  /** The number of sales made by the reseller */
  salesCount: number
}
