/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface SaleReturnProductDto {
  /** The ID of the product */
  productId: string
  /** The ID of the product model */
  productModelId: string
  /** The name of the product model */
  productModelName: string
  /** The sale price of the product */
  salePrice: number
}
