/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { SaleByResellerReturnDtoPaymentMethod } from './saleByResellerReturnDtoPaymentMethod'
import type { SaleByResellerReturnDtoStatus } from './saleByResellerReturnDtoStatus'
import type { SaleReturnProductDto } from './saleReturnProductDto'

export interface SaleByResellerReturnDto {
  /** The ID of the sale */
  id: string
  /** The ID of the consumer */
  customerId: string
  /** The name of the consumer */
  customerName: string
  /** The phone number of the consumer */
  customerPhone: string
  /** The IDs of the products in the sale */
  products: SaleReturnProductDto[]
  /** The date of the sale */
  saleDate: string
  /** The total amount of the sale */
  totalAmount: string
  /** The payment method of the sale */
  paymentMethod: SaleByResellerReturnDtoPaymentMethod
  /** The number of installments of the sale */
  numberInstallments: number
  /** The status of the sale */
  status: SaleByResellerReturnDtoStatus
}
