/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the sale
 */
export type SaleStatus = (typeof SaleStatus)[keyof typeof SaleStatus]

export const SaleStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  INSTALLMENTS_PENDING: 'INSTALLMENTS_PENDING',
  INSTALLMENTS_PAID: 'INSTALLMENTS_PAID',
  INSTALLMENTS_OVERDUE: 'INSTALLMENTS_OVERDUE'
} as const
