/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The payment method of the sale
 */
export type SaleReturnDtoPaymentMethod =
  (typeof SaleReturnDtoPaymentMethod)[keyof typeof SaleReturnDtoPaymentMethod]

export const SaleReturnDtoPaymentMethod = {
  CASH: 'CASH',
  PIX: 'PIX',
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT',
  EXCHANGE: 'EXCHANGE'
} as const
