/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface SellingProductDto {
  /** The ID of the product model */
  modelId: string
  /** The name of the product model */
  modelName: string
  /** The quantity of the product */
  quantity: number
  /** The sale price of the product */
  salePrice: string
  /** The total value of the product */
  totalValue: string
}
