/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the shipment
 */
export type ShipmentStatus =
  (typeof ShipmentStatus)[keyof typeof ShipmentStatus]

export const ShipmentStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
} as const
