/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { PhoneNumber } from './phoneNumber'
import type { SupplierName } from './supplierName'

export interface Supplier {
  /** The ID of the supplier */
  id: string
  /** The name of the supplier */
  name: SupplierName
  /** The phone number of the supplier */
  phone: PhoneNumber
}
