/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface TotalSalesByResellerDto {
  /** The ID of the reseller */
  resellerId: string
  /** The name of the reseller */
  resellerName: string
  /** The number of sales made by the reseller */
  salesCount: number
}
