/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface TotalReturnsInPeriodDto {
  /** The start date of the period */
  start: string
  /** The end date of the period */
  end: string
  /** The total returns in the period */
  totalReturns: number
}
