/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { UpdateProductModelDtoStatus } from './updateProductModelDtoStatus'

export interface UpdateProductModelDto {
  /** The name of the product model */
  name?: string
  /** The ID of the category */
  categoryId?: string
  /** The suggested price of the product model */
  suggestedPrice?: string
  /** The description of the product model */
  description?: string
  /** The photo of the product model */
  photo?: Blob
  /** The photo URL of the product model */
  photoUrl?: string
  /** The status of the product model */
  status?: UpdateProductModelDtoStatus
}
