/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { UpdateSaleStatusDtoStatus } from './updateSaleStatusDtoStatus'

export interface UpdateSaleStatusDto {
  /** The new status of the sale */
  status: UpdateSaleStatusDtoStatus
}
