/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface UpdateProductDto {
  /** The unit cost of the product */
  unitCost?: string
  /** The sale price of the product */
  salePrice?: string
  /** The status of the product */
  status?: string
}
