/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { UpdateReturnStatusDtoStatus } from './updateReturnStatusDtoStatus'

export interface UpdateReturnStatusDto {
  /** The status of the return */
  status: UpdateReturnStatusDtoStatus
}
