/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { OwnershipTransferStatus } from './ownershipTransferStatus'

export interface UpdateOwnershipTransferStatusDto {
  /** The new status of the ownership transfer */
  status: OwnershipTransferStatus
}
