/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

export interface UpdateSupplierDto {
  /** The name of the supplier */
  name?: string
  /** The phone number of the supplier */
  phone?: string
}
