/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { UserStatus } from './userStatus'

export interface UpdateUserStatusDto {
  /** The new status for the user */
  status: UserStatus
}
