/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Country } from './country'
import type { FederativeUnit } from './federativeUnit'

export interface UpdateUserDto {
  /**
   * The new name for the user
   * @minLength 2
   * @maxLength 50
   */
  name?: string
  /**
   * The new last name for the user
   * @minLength 2
   * @maxLength 50
   */
  surname?: string
  /** The new phone number for the user */
  phone?: string
  /** The new email for the user */
  email?: string
  /** The new password for the user */
  password?: string
  /** The new street for the user */
  street?: string
  /** The new number for the user */
  number?: number
  /** The new complement for the user */
  complement?: string
  /** The new neighborhood for the user */
  neighborhood?: string
  /** The new city for the user */
  city?: string
  /** The new federative unit for the user */
  federativeUnit?: FederativeUnit
  /** The new postal code for the user */
  postalCode?: string
  /** The new country for the user */
  country?: Country
}
