/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The status of the user
 */
export type UserStatusProperty =
  (typeof UserStatusProperty)[keyof typeof UserStatusProperty]

export const UserStatusProperty = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  PENDING: 'PENDING'
} as const
