/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * Product status
 */
export type UserProductDtoStatus =
  (typeof UserProductDtoStatus)[keyof typeof UserProductDtoStatus]

export const UserProductDtoStatus = {
  IN_STOCK: 'IN_STOCK',
  ASSIGNED: 'ASSIGNED',
  SOLD: 'SOLD'
} as const
