/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */

/**
 * The role of the user
 */
export type UserRole = (typeof UserRole)[keyof typeof UserRole]

export const UserRole = {
  ADMIN: 'ADMIN',
  RESELLER: 'RESELLER',
  ASSISTANT: 'ASSISTANT',
  UNASSIGNED: 'UNASSIGNED'
} as const
