/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import type { Role } from './role'
import type { UserStatus } from './userStatus'

export interface UserPayloadDto {
  /** The unique identifier of the user */
  id: string
  /** The email address of the user */
  email: string
  /** The role of the user */
  role: Role
  /** The status of the user */
  status: UserStatus
  /** The name of the user */
  name: string
}
