/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { Product, UpdateProductDto } from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get all products
 */
export type getAllProductsResponse200 = {
  data: Product[]
  status: 200
}

export type getAllProductsResponse401 = {
  data: void
  status: 401
}

export type getAllProductsResponse403 = {
  data: void
  status: 403
}

export type getAllProductsResponseSuccess = getAllProductsResponse200 & {
  headers: Headers
}
export type getAllProductsResponseError = (
  | getAllProductsResponse401
  | getAllProductsResponse403
) & {
  headers: Headers
}

export type getAllProductsResponse =
  | getAllProductsResponseSuccess
  | getAllProductsResponseError

export const getGetAllProductsUrl = () => {
  return `/products`
}

export const getAllProducts = async (
  options?: RequestInit
): Promise<getAllProductsResponse> => {
  return customInstance<getAllProductsResponse>(getGetAllProductsUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllProductsQueryKey = () => {
  return [`/products`] as const
}

export const getGetAllProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllProductsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllProducts>>> = ({
    signal
  }) => getAllProducts({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllProducts>>
>
export type GetAllProductsQueryError = ErrorType<void>

export function useGetAllProducts<
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllProducts<
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllProducts>>,
          TError,
          Awaited<ReturnType<typeof getAllProducts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllProducts<
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all products
 */

export function useGetAllProducts<
  TData = Awaited<ReturnType<typeof getAllProducts>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllProducts>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get available products (IN_STOCK)
 */
export type getAvailableProductsResponse200 = {
  data: Product[]
  status: 200
}

export type getAvailableProductsResponse401 = {
  data: void
  status: 401
}

export type getAvailableProductsResponse403 = {
  data: void
  status: 403
}

export type getAvailableProductsResponseSuccess =
  getAvailableProductsResponse200 & {
    headers: Headers
  }
export type getAvailableProductsResponseError = (
  | getAvailableProductsResponse401
  | getAvailableProductsResponse403
) & {
  headers: Headers
}

export type getAvailableProductsResponse =
  | getAvailableProductsResponseSuccess
  | getAvailableProductsResponseError

export const getGetAvailableProductsUrl = () => {
  return `/products/available/in-stock`
}

export const getAvailableProducts = async (
  options?: RequestInit
): Promise<getAvailableProductsResponse> => {
  return customInstance<getAvailableProductsResponse>(
    getGetAvailableProductsUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getGetAvailableProductsQueryKey = () => {
  return [`/products/available/in-stock`] as const
}

export const getGetAvailableProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAvailableProducts>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAvailableProducts>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAvailableProductsQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAvailableProducts>>
  > = ({ signal }) => getAvailableProducts({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAvailableProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvailableProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAvailableProducts>>
>
export type GetAvailableProductsQueryError = ErrorType<void>

export function useGetAvailableProducts<
  TData = Awaited<ReturnType<typeof getAvailableProducts>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailableProducts>>,
          TError,
          Awaited<ReturnType<typeof getAvailableProducts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAvailableProducts<
  TData = Awaited<ReturnType<typeof getAvailableProducts>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailableProducts>>,
          TError,
          Awaited<ReturnType<typeof getAvailableProducts>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAvailableProducts<
  TData = Awaited<ReturnType<typeof getAvailableProducts>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableProducts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get available products (IN_STOCK)
 */

export function useGetAvailableProducts<
  TData = Awaited<ReturnType<typeof getAvailableProducts>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableProducts>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAvailableProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a specific product
 */
export type getOneProductResponse200 = {
  data: Product
  status: 200
}

export type getOneProductResponse401 = {
  data: void
  status: 401
}

export type getOneProductResponse403 = {
  data: void
  status: 403
}

export type getOneProductResponse404 = {
  data: void
  status: 404
}

export type getOneProductResponseSuccess = getOneProductResponse200 & {
  headers: Headers
}
export type getOneProductResponseError = (
  | getOneProductResponse401
  | getOneProductResponse403
  | getOneProductResponse404
) & {
  headers: Headers
}

export type getOneProductResponse =
  | getOneProductResponseSuccess
  | getOneProductResponseError

export const getGetOneProductUrl = (id: string) => {
  return `/products/${id}`
}

export const getOneProduct = async (
  id: string,
  options?: RequestInit
): Promise<getOneProductResponse> => {
  return customInstance<getOneProductResponse>(getGetOneProductUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneProductQueryKey = (id: string) => {
  return [`/products/${id}`] as const
}

export const getGetOneProductQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneProduct>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneProduct>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneProductQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneProduct>>> = ({
    signal
  }) => getOneProduct(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneProduct>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneProductQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneProduct>>
>
export type GetOneProductQueryError = ErrorType<void>

export function useGetOneProduct<
  TData = Awaited<ReturnType<typeof getOneProduct>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneProduct>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneProduct>>,
          TError,
          Awaited<ReturnType<typeof getOneProduct>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneProduct<
  TData = Awaited<ReturnType<typeof getOneProduct>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneProduct>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneProduct>>,
          TError,
          Awaited<ReturnType<typeof getOneProduct>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneProduct<
  TData = Awaited<ReturnType<typeof getOneProduct>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneProduct>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific product
 */

export function useGetOneProduct<
  TData = Awaited<ReturnType<typeof getOneProduct>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneProduct>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneProductQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a product
 */
export type updateProductResponse200 = {
  data: Product
  status: 200
}

export type updateProductResponse401 = {
  data: void
  status: 401
}

export type updateProductResponse403 = {
  data: void
  status: 403
}

export type updateProductResponseSuccess = updateProductResponse200 & {
  headers: Headers
}
export type updateProductResponseError = (
  | updateProductResponse401
  | updateProductResponse403
) & {
  headers: Headers
}

export type updateProductResponse =
  | updateProductResponseSuccess
  | updateProductResponseError

export const getUpdateProductUrl = (id: string) => {
  return `/products/${id}`
}

export const updateProduct = async (
  id: string,
  updateProductDto: UpdateProductDto,
  options?: RequestInit
): Promise<updateProductResponse> => {
  return customInstance<updateProductResponse>(getUpdateProductUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProductDto)
  })
}

export const getUpdateProductMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProduct>>,
    TError,
    { id: string; data: UpdateProductDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProduct>>,
  TError,
  { id: string; data: UpdateProductDto },
  TContext
> => {
  const mutationKey = ['updateProduct']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProduct>>,
    { id: string; data: UpdateProductDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateProduct(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProduct>>
>
export type UpdateProductMutationBody = UpdateProductDto
export type UpdateProductMutationError = ErrorType<void>

/**
 * @summary Update a product
 */
export const useUpdateProduct = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProduct>>,
      TError,
      { id: string; data: UpdateProductDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateProduct>>,
  TError,
  { id: string; data: UpdateProductDto },
  TContext
> => {
  return useMutation(getUpdateProductMutationOptions(options), queryClient)
}
/**
 * @summary Delete a product
 */
export type deleteProductResponse204 = {
  data: void
  status: 204
}

export type deleteProductResponse401 = {
  data: void
  status: 401
}

export type deleteProductResponse403 = {
  data: void
  status: 403
}

export type deleteProductResponseSuccess = deleteProductResponse204 & {
  headers: Headers
}
export type deleteProductResponseError = (
  | deleteProductResponse401
  | deleteProductResponse403
) & {
  headers: Headers
}

export type deleteProductResponse =
  | deleteProductResponseSuccess
  | deleteProductResponseError

export const getDeleteProductUrl = (id: string) => {
  return `/products/${id}`
}

export const deleteProduct = async (
  id: string,
  options?: RequestInit
): Promise<deleteProductResponse> => {
  return customInstance<deleteProductResponse>(getDeleteProductUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

export const getDeleteProductMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProduct>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProduct>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteProduct']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProduct>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteProduct(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProduct>>
>

export type DeleteProductMutationError = ErrorType<void>

/**
 * @summary Delete a product
 */
export const useDeleteProduct = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteProduct>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteProduct>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteProductMutationOptions(options), queryClient)
}
/**
 * @summary Sell a product
 */
export type sellProductResponse204 = {
  data: void
  status: 204
}

export type sellProductResponse401 = {
  data: void
  status: 401
}

export type sellProductResponse403 = {
  data: void
  status: 403
}

export type sellProductResponseSuccess = sellProductResponse204 & {
  headers: Headers
}
export type sellProductResponseError = (
  | sellProductResponse401
  | sellProductResponse403
) & {
  headers: Headers
}

export type sellProductResponse =
  | sellProductResponseSuccess
  | sellProductResponseError

export const getSellProductUrl = (id: string) => {
  return `/products/${id}/sell`
}

export const sellProduct = async (
  id: string,
  options?: RequestInit
): Promise<sellProductResponse> => {
  return customInstance<sellProductResponse>(getSellProductUrl(id), {
    ...options,
    method: 'PATCH'
  })
}

export const getSellProductMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sellProduct>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof sellProduct>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['sellProduct']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sellProduct>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return sellProduct(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SellProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof sellProduct>>
>

export type SellProductMutationError = ErrorType<void>

/**
 * @summary Sell a product
 */
export const useSellProduct = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sellProduct>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof sellProduct>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getSellProductMutationOptions(options), queryClient)
}
