/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'

import type {
  ParamsDto,
  ProductInInventoryDto,
  SellingProductDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get top selling products for a reseller
 */
export type resellerProductKpiGetTopSellingProductsResponse200 = {
  data: SellingProductDto[]
  status: 200
}

export type resellerProductKpiGetTopSellingProductsResponse401 = {
  data: void
  status: 401
}

export type resellerProductKpiGetTopSellingProductsResponse403 = {
  data: void
  status: 403
}

export type resellerProductKpiGetTopSellingProductsResponseSuccess =
  resellerProductKpiGetTopSellingProductsResponse200 & {
    headers: Headers
  }
export type resellerProductKpiGetTopSellingProductsResponseError = (
  | resellerProductKpiGetTopSellingProductsResponse401
  | resellerProductKpiGetTopSellingProductsResponse403
) & {
  headers: Headers
}

export type resellerProductKpiGetTopSellingProductsResponse =
  | resellerProductKpiGetTopSellingProductsResponseSuccess
  | resellerProductKpiGetTopSellingProductsResponseError

export const getResellerProductKpiGetTopSellingProductsUrl = () => {
  return `/kpi/my-space/products/top-selling`
}

export const resellerProductKpiGetTopSellingProducts = async (
  paramsDto: ParamsDto,
  options?: RequestInit
): Promise<resellerProductKpiGetTopSellingProductsResponse> => {
  return customInstance<resellerProductKpiGetTopSellingProductsResponse>(
    getResellerProductKpiGetTopSellingProductsUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getResellerProductKpiGetTopSellingProductsMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resellerProductKpiGetTopSellingProducts>>,
    TError,
    { data: ParamsDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof resellerProductKpiGetTopSellingProducts>>,
  TError,
  { data: ParamsDto },
  TContext
> => {
  const mutationKey = ['resellerProductKpiGetTopSellingProducts']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resellerProductKpiGetTopSellingProducts>>,
    { data: ParamsDto }
  > = (props) => {
    const { data } = props ?? {}

    return resellerProductKpiGetTopSellingProducts(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResellerProductKpiGetTopSellingProductsMutationResult = NonNullable<
  Awaited<ReturnType<typeof resellerProductKpiGetTopSellingProducts>>
>
export type ResellerProductKpiGetTopSellingProductsMutationBody = ParamsDto
export type ResellerProductKpiGetTopSellingProductsMutationError =
  ErrorType<void>

/**
 * @summary Get top selling products for a reseller
 */
export const useResellerProductKpiGetTopSellingProducts = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resellerProductKpiGetTopSellingProducts>>,
      TError,
      { data: ParamsDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof resellerProductKpiGetTopSellingProducts>>,
  TError,
  { data: ParamsDto },
  TContext
> => {
  return useMutation(
    getResellerProductKpiGetTopSellingProductsMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Get products with longest time in inventory for a reseller
 */
export type resellerProductKpiGetProductsWithLongestTimeInInventoryResponse200 =
  {
    data: ProductInInventoryDto[]
    status: 200
  }

export type resellerProductKpiGetProductsWithLongestTimeInInventoryResponse401 =
  {
    data: void
    status: 401
  }

export type resellerProductKpiGetProductsWithLongestTimeInInventoryResponse403 =
  {
    data: void
    status: 403
  }

export type resellerProductKpiGetProductsWithLongestTimeInInventoryResponseSuccess =
  resellerProductKpiGetProductsWithLongestTimeInInventoryResponse200 & {
    headers: Headers
  }
export type resellerProductKpiGetProductsWithLongestTimeInInventoryResponseError =
  (
    | resellerProductKpiGetProductsWithLongestTimeInInventoryResponse401
    | resellerProductKpiGetProductsWithLongestTimeInInventoryResponse403
  ) & {
    headers: Headers
  }

export type resellerProductKpiGetProductsWithLongestTimeInInventoryResponse =
  | resellerProductKpiGetProductsWithLongestTimeInInventoryResponseSuccess
  | resellerProductKpiGetProductsWithLongestTimeInInventoryResponseError

export const getResellerProductKpiGetProductsWithLongestTimeInInventoryUrl =
  () => {
    return `/kpi/my-space/products/longest-time-in-inventory`
  }

export const resellerProductKpiGetProductsWithLongestTimeInInventory = async (
  paramsDto: ParamsDto,
  options?: RequestInit
): Promise<resellerProductKpiGetProductsWithLongestTimeInInventoryResponse> => {
  return customInstance<resellerProductKpiGetProductsWithLongestTimeInInventoryResponse>(
    getResellerProductKpiGetProductsWithLongestTimeInInventoryUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getResellerProductKpiGetProductsWithLongestTimeInInventoryMutationOptions =
  <TError = ErrorType<void>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof resellerProductKpiGetProductsWithLongestTimeInInventory
        >
      >,
      TError,
      { data: ParamsDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof resellerProductKpiGetProductsWithLongestTimeInInventory>
    >,
    TError,
    { data: ParamsDto },
    TContext
  > => {
    const mutationKey = [
      'resellerProductKpiGetProductsWithLongestTimeInInventory'
    ]
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        'mutationKey' in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined }

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<
          typeof resellerProductKpiGetProductsWithLongestTimeInInventory
        >
      >,
      { data: ParamsDto }
    > = (props) => {
      const { data } = props ?? {}

      return resellerProductKpiGetProductsWithLongestTimeInInventory(
        data,
        requestOptions
      )
    }

    return { mutationFn, ...mutationOptions }
  }

export type ResellerProductKpiGetProductsWithLongestTimeInInventoryMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof resellerProductKpiGetProductsWithLongestTimeInInventory>
    >
  >
export type ResellerProductKpiGetProductsWithLongestTimeInInventoryMutationBody =
  ParamsDto
export type ResellerProductKpiGetProductsWithLongestTimeInInventoryMutationError =
  ErrorType<void>

/**
 * @summary Get products with longest time in inventory for a reseller
 */
export const useResellerProductKpiGetProductsWithLongestTimeInInventory = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<
          typeof resellerProductKpiGetProductsWithLongestTimeInInventory
        >
      >,
      TError,
      { data: ParamsDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<
    ReturnType<typeof resellerProductKpiGetProductsWithLongestTimeInInventory>
  >,
  TError,
  { data: ParamsDto },
  TContext
> => {
  return useMutation(
    getResellerProductKpiGetProductsWithLongestTimeInInventoryMutationOptions(
      options
    ),
    queryClient
  )
}
