/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  CreateOwnershipTransferDto,
  OwnershipTransfer,
  OwnershipTransferWithSerialDto,
  UpdateOwnershipTransferDto,
  UpdateOwnershipTransferStatusDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get all ownership transfers
 */
export type getAllOwnershipTransfersResponse200 = {
  data: OwnershipTransferWithSerialDto[]
  status: 200
}

export type getAllOwnershipTransfersResponse401 = {
  data: void
  status: 401
}

export type getAllOwnershipTransfersResponse403 = {
  data: void
  status: 403
}

export type getAllOwnershipTransfersResponseSuccess =
  getAllOwnershipTransfersResponse200 & {
    headers: Headers
  }
export type getAllOwnershipTransfersResponseError = (
  | getAllOwnershipTransfersResponse401
  | getAllOwnershipTransfersResponse403
) & {
  headers: Headers
}

export type getAllOwnershipTransfersResponse =
  | getAllOwnershipTransfersResponseSuccess
  | getAllOwnershipTransfersResponseError

export const getGetAllOwnershipTransfersUrl = () => {
  return `/ownership-transfers`
}

export const getAllOwnershipTransfers = async (
  options?: RequestInit
): Promise<getAllOwnershipTransfersResponse> => {
  return customInstance<getAllOwnershipTransfersResponse>(
    getGetAllOwnershipTransfersUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getGetAllOwnershipTransfersQueryKey = () => {
  return [`/ownership-transfers`] as const
}

export const getGetAllOwnershipTransfersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetAllOwnershipTransfersQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllOwnershipTransfers>>
  > = ({ signal }) => getAllOwnershipTransfers({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllOwnershipTransfersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllOwnershipTransfers>>
>
export type GetAllOwnershipTransfersQueryError = ErrorType<void>

export function useGetAllOwnershipTransfers<
  TData = Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
          TError,
          Awaited<ReturnType<typeof getAllOwnershipTransfers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllOwnershipTransfers<
  TData = Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
          TError,
          Awaited<ReturnType<typeof getAllOwnershipTransfers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllOwnershipTransfers<
  TData = Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all ownership transfers
 */

export function useGetAllOwnershipTransfers<
  TData = Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllOwnershipTransfers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllOwnershipTransfersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Create a new ownership transfer
 */
export type createOwnershipTransferResponse201 = {
  data: OwnershipTransfer
  status: 201
}

export type createOwnershipTransferResponse401 = {
  data: void
  status: 401
}

export type createOwnershipTransferResponse403 = {
  data: void
  status: 403
}

export type createOwnershipTransferResponseSuccess =
  createOwnershipTransferResponse201 & {
    headers: Headers
  }
export type createOwnershipTransferResponseError = (
  | createOwnershipTransferResponse401
  | createOwnershipTransferResponse403
) & {
  headers: Headers
}

export type createOwnershipTransferResponse =
  | createOwnershipTransferResponseSuccess
  | createOwnershipTransferResponseError

export const getCreateOwnershipTransferUrl = () => {
  return `/ownership-transfers`
}

export const createOwnershipTransfer = async (
  createOwnershipTransferDto: CreateOwnershipTransferDto,
  options?: RequestInit
): Promise<createOwnershipTransferResponse> => {
  return customInstance<createOwnershipTransferResponse>(
    getCreateOwnershipTransferUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createOwnershipTransferDto)
    }
  )
}

export const getCreateOwnershipTransferMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOwnershipTransfer>>,
    TError,
    { data: CreateOwnershipTransferDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOwnershipTransfer>>,
  TError,
  { data: CreateOwnershipTransferDto },
  TContext
> => {
  const mutationKey = ['createOwnershipTransfer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOwnershipTransfer>>,
    { data: CreateOwnershipTransferDto }
  > = (props) => {
    const { data } = props ?? {}

    return createOwnershipTransfer(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateOwnershipTransferMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOwnershipTransfer>>
>
export type CreateOwnershipTransferMutationBody = CreateOwnershipTransferDto
export type CreateOwnershipTransferMutationError = ErrorType<void>

/**
 * @summary Create a new ownership transfer
 */
export const useCreateOwnershipTransfer = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createOwnershipTransfer>>,
      TError,
      { data: CreateOwnershipTransferDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createOwnershipTransfer>>,
  TError,
  { data: CreateOwnershipTransferDto },
  TContext
> => {
  return useMutation(
    getCreateOwnershipTransferMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Get a specific ownership transfer
 */
export type getOneOwnershipTransferResponse200 = {
  data: OwnershipTransferWithSerialDto
  status: 200
}

export type getOneOwnershipTransferResponse401 = {
  data: void
  status: 401
}

export type getOneOwnershipTransferResponse403 = {
  data: void
  status: 403
}

export type getOneOwnershipTransferResponse404 = {
  data: void
  status: 404
}

export type getOneOwnershipTransferResponseSuccess =
  getOneOwnershipTransferResponse200 & {
    headers: Headers
  }
export type getOneOwnershipTransferResponseError = (
  | getOneOwnershipTransferResponse401
  | getOneOwnershipTransferResponse403
  | getOneOwnershipTransferResponse404
) & {
  headers: Headers
}

export type getOneOwnershipTransferResponse =
  | getOneOwnershipTransferResponseSuccess
  | getOneOwnershipTransferResponseError

export const getGetOneOwnershipTransferUrl = (id: string) => {
  return `/ownership-transfers/${id}`
}

export const getOneOwnershipTransfer = async (
  id: string,
  options?: RequestInit
): Promise<getOneOwnershipTransferResponse> => {
  return customInstance<getOneOwnershipTransferResponse>(
    getGetOneOwnershipTransferUrl(id),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getGetOneOwnershipTransferQueryKey = (id: string) => {
  return [`/ownership-transfers/${id}`] as const
}

export const getGetOneOwnershipTransferQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetOneOwnershipTransferQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOneOwnershipTransfer>>
  > = ({ signal }) => getOneOwnershipTransfer(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneOwnershipTransferQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneOwnershipTransfer>>
>
export type GetOneOwnershipTransferQueryError = ErrorType<void>

export function useGetOneOwnershipTransfer<
  TData = Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
          TError,
          Awaited<ReturnType<typeof getOneOwnershipTransfer>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneOwnershipTransfer<
  TData = Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
          TError,
          Awaited<ReturnType<typeof getOneOwnershipTransfer>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneOwnershipTransfer<
  TData = Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific ownership transfer
 */

export function useGetOneOwnershipTransfer<
  TData = Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOneOwnershipTransfer>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneOwnershipTransferQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a ownership transfer
 */
export type updateOwnershipTransferResponse200 = {
  data: OwnershipTransferWithSerialDto
  status: 200
}

export type updateOwnershipTransferResponse401 = {
  data: void
  status: 401
}

export type updateOwnershipTransferResponse403 = {
  data: void
  status: 403
}

export type updateOwnershipTransferResponseSuccess =
  updateOwnershipTransferResponse200 & {
    headers: Headers
  }
export type updateOwnershipTransferResponseError = (
  | updateOwnershipTransferResponse401
  | updateOwnershipTransferResponse403
) & {
  headers: Headers
}

export type updateOwnershipTransferResponse =
  | updateOwnershipTransferResponseSuccess
  | updateOwnershipTransferResponseError

export const getUpdateOwnershipTransferUrl = (id: string) => {
  return `/ownership-transfers/${id}`
}

export const updateOwnershipTransfer = async (
  id: string,
  updateOwnershipTransferDto: UpdateOwnershipTransferDto,
  options?: RequestInit
): Promise<updateOwnershipTransferResponse> => {
  return customInstance<updateOwnershipTransferResponse>(
    getUpdateOwnershipTransferUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateOwnershipTransferDto)
    }
  )
}

export const getUpdateOwnershipTransferMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateOwnershipTransfer>>,
    TError,
    { id: string; data: UpdateOwnershipTransferDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateOwnershipTransfer>>,
  TError,
  { id: string; data: UpdateOwnershipTransferDto },
  TContext
> => {
  const mutationKey = ['updateOwnershipTransfer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateOwnershipTransfer>>,
    { id: string; data: UpdateOwnershipTransferDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateOwnershipTransfer(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateOwnershipTransferMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateOwnershipTransfer>>
>
export type UpdateOwnershipTransferMutationBody = UpdateOwnershipTransferDto
export type UpdateOwnershipTransferMutationError = ErrorType<void>

/**
 * @summary Update a ownership transfer
 */
export const useUpdateOwnershipTransfer = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateOwnershipTransfer>>,
      TError,
      { id: string; data: UpdateOwnershipTransferDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateOwnershipTransfer>>,
  TError,
  { id: string; data: UpdateOwnershipTransferDto },
  TContext
> => {
  return useMutation(
    getUpdateOwnershipTransferMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Delete a ownership transfer
 */
export type deleteOwnershipTransferResponse204 = {
  data: void
  status: 204
}

export type deleteOwnershipTransferResponse401 = {
  data: void
  status: 401
}

export type deleteOwnershipTransferResponse403 = {
  data: void
  status: 403
}

export type deleteOwnershipTransferResponseSuccess =
  deleteOwnershipTransferResponse204 & {
    headers: Headers
  }
export type deleteOwnershipTransferResponseError = (
  | deleteOwnershipTransferResponse401
  | deleteOwnershipTransferResponse403
) & {
  headers: Headers
}

export type deleteOwnershipTransferResponse =
  | deleteOwnershipTransferResponseSuccess
  | deleteOwnershipTransferResponseError

export const getDeleteOwnershipTransferUrl = (id: string) => {
  return `/ownership-transfers/${id}`
}

export const deleteOwnershipTransfer = async (
  id: string,
  options?: RequestInit
): Promise<deleteOwnershipTransferResponse> => {
  return customInstance<deleteOwnershipTransferResponse>(
    getDeleteOwnershipTransferUrl(id),
    {
      ...options,
      method: 'DELETE'
    }
  )
}

export const getDeleteOwnershipTransferMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOwnershipTransfer>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOwnershipTransfer>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteOwnershipTransfer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOwnershipTransfer>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteOwnershipTransfer(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteOwnershipTransferMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOwnershipTransfer>>
>

export type DeleteOwnershipTransferMutationError = ErrorType<void>

/**
 * @summary Delete a ownership transfer
 */
export const useDeleteOwnershipTransfer = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteOwnershipTransfer>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteOwnershipTransfer>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteOwnershipTransferMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Update the status of a ownership transfer
 */
export type updateOwnershipTransferStatusResponse200 = {
  data: void
  status: 200
}

export type updateOwnershipTransferStatusResponse401 = {
  data: void
  status: 401
}

export type updateOwnershipTransferStatusResponse403 = {
  data: void
  status: 403
}

export type updateOwnershipTransferStatusResponseSuccess =
  updateOwnershipTransferStatusResponse200 & {
    headers: Headers
  }
export type updateOwnershipTransferStatusResponseError = (
  | updateOwnershipTransferStatusResponse401
  | updateOwnershipTransferStatusResponse403
) & {
  headers: Headers
}

export type updateOwnershipTransferStatusResponse =
  | updateOwnershipTransferStatusResponseSuccess
  | updateOwnershipTransferStatusResponseError

export const getUpdateOwnershipTransferStatusUrl = (id: string) => {
  return `/ownership-transfers/${id}/status`
}

export const updateOwnershipTransferStatus = async (
  id: string,
  updateOwnershipTransferStatusDto: UpdateOwnershipTransferStatusDto,
  options?: RequestInit
): Promise<updateOwnershipTransferStatusResponse> => {
  return customInstance<updateOwnershipTransferStatusResponse>(
    getUpdateOwnershipTransferStatusUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateOwnershipTransferStatusDto)
    }
  )
}

export const getUpdateOwnershipTransferStatusMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateOwnershipTransferStatus>>,
    TError,
    { id: string; data: UpdateOwnershipTransferStatusDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateOwnershipTransferStatus>>,
  TError,
  { id: string; data: UpdateOwnershipTransferStatusDto },
  TContext
> => {
  const mutationKey = ['updateOwnershipTransferStatus']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateOwnershipTransferStatus>>,
    { id: string; data: UpdateOwnershipTransferStatusDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateOwnershipTransferStatus(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateOwnershipTransferStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateOwnershipTransferStatus>>
>
export type UpdateOwnershipTransferStatusMutationBody =
  UpdateOwnershipTransferStatusDto
export type UpdateOwnershipTransferStatusMutationError = ErrorType<void>

/**
 * @summary Update the status of a ownership transfer
 */
export const useUpdateOwnershipTransferStatus = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateOwnershipTransferStatus>>,
      TError,
      { id: string; data: UpdateOwnershipTransferStatusDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateOwnershipTransferStatus>>,
  TError,
  { id: string; data: UpdateOwnershipTransferStatusDto },
  TContext
> => {
  return useMutation(
    getUpdateOwnershipTransferStatusMutationOptions(options),
    queryClient
  )
}
