/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { Category, CreateCategoryDto, UpdateCategoryDto } from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get all categories
 */
export type getAllCategoriesResponse200 = {
  data: Category[]
  status: 200
}

export type getAllCategoriesResponse401 = {
  data: void
  status: 401
}

export type getAllCategoriesResponse403 = {
  data: void
  status: 403
}

export type getAllCategoriesResponseSuccess = getAllCategoriesResponse200 & {
  headers: Headers
}
export type getAllCategoriesResponseError = (
  | getAllCategoriesResponse401
  | getAllCategoriesResponse403
) & {
  headers: Headers
}

export type getAllCategoriesResponse =
  | getAllCategoriesResponseSuccess
  | getAllCategoriesResponseError

export const getGetAllCategoriesUrl = () => {
  return `/categories`
}

export const getAllCategories = async (
  options?: RequestInit
): Promise<getAllCategoriesResponse> => {
  return customInstance<getAllCategoriesResponse>(getGetAllCategoriesUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllCategoriesQueryKey = () => {
  return [`/categories`] as const
}

export const getGetAllCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllCategories>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllCategoriesQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllCategories>>
  > = ({ signal }) => getAllCategories({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllCategories>>
>
export type GetAllCategoriesQueryError = ErrorType<void>

export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllCategories>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCategories>>,
          TError,
          Awaited<ReturnType<typeof getAllCategories>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all categories
 */

export function useGetAllCategories<
  TData = Awaited<ReturnType<typeof getAllCategories>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCategories>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllCategoriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Create a new category
 */
export type createCategoryResponse201 = {
  data: Category
  status: 201
}

export type createCategoryResponse401 = {
  data: void
  status: 401
}

export type createCategoryResponse403 = {
  data: void
  status: 403
}

export type createCategoryResponseSuccess = createCategoryResponse201 & {
  headers: Headers
}
export type createCategoryResponseError = (
  | createCategoryResponse401
  | createCategoryResponse403
) & {
  headers: Headers
}

export type createCategoryResponse =
  | createCategoryResponseSuccess
  | createCategoryResponseError

export const getCreateCategoryUrl = () => {
  return `/categories`
}

export const createCategory = async (
  createCategoryDto: CreateCategoryDto,
  options?: RequestInit
): Promise<createCategoryResponse> => {
  return customInstance<createCategoryResponse>(getCreateCategoryUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCategoryDto)
  })
}

export const getCreateCategoryMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCategory>>,
    TError,
    { data: CreateCategoryDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: CreateCategoryDto },
  TContext
> => {
  const mutationKey = ['createCategory']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCategory>>,
    { data: CreateCategoryDto }
  > = (props) => {
    const { data } = props ?? {}

    return createCategory(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCategory>>
>
export type CreateCategoryMutationBody = CreateCategoryDto
export type CreateCategoryMutationError = ErrorType<void>

/**
 * @summary Create a new category
 */
export const useCreateCategory = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCategory>>,
      TError,
      { data: CreateCategoryDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createCategory>>,
  TError,
  { data: CreateCategoryDto },
  TContext
> => {
  return useMutation(getCreateCategoryMutationOptions(options), queryClient)
}
/**
 * @summary Get a specific category
 */
export type getOneCategoryResponse200 = {
  data: Category
  status: 200
}

export type getOneCategoryResponse401 = {
  data: void
  status: 401
}

export type getOneCategoryResponse403 = {
  data: void
  status: 403
}

export type getOneCategoryResponse404 = {
  data: void
  status: 404
}

export type getOneCategoryResponseSuccess = getOneCategoryResponse200 & {
  headers: Headers
}
export type getOneCategoryResponseError = (
  | getOneCategoryResponse401
  | getOneCategoryResponse403
  | getOneCategoryResponse404
) & {
  headers: Headers
}

export type getOneCategoryResponse =
  | getOneCategoryResponseSuccess
  | getOneCategoryResponseError

export const getGetOneCategoryUrl = (id: string) => {
  return `/categories/${id}`
}

export const getOneCategory = async (
  id: string,
  options?: RequestInit
): Promise<getOneCategoryResponse> => {
  return customInstance<getOneCategoryResponse>(getGetOneCategoryUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneCategoryQueryKey = (id: string) => {
  return [`/categories/${id}`] as const
}

export const getGetOneCategoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneCategory>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCategory>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneCategoryQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneCategory>>> = ({
    signal
  }) => getOneCategory(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneCategory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneCategoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneCategory>>
>
export type GetOneCategoryQueryError = ErrorType<void>

export function useGetOneCategory<
  TData = Awaited<ReturnType<typeof getOneCategory>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCategory>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneCategory>>,
          TError,
          Awaited<ReturnType<typeof getOneCategory>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneCategory<
  TData = Awaited<ReturnType<typeof getOneCategory>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCategory>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneCategory>>,
          TError,
          Awaited<ReturnType<typeof getOneCategory>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneCategory<
  TData = Awaited<ReturnType<typeof getOneCategory>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCategory>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific category
 */

export function useGetOneCategory<
  TData = Awaited<ReturnType<typeof getOneCategory>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCategory>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneCategoryQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a category
 */
export type updateCategoryResponse200 = {
  data: Category
  status: 200
}

export type updateCategoryResponse401 = {
  data: void
  status: 401
}

export type updateCategoryResponse403 = {
  data: void
  status: 403
}

export type updateCategoryResponseSuccess = updateCategoryResponse200 & {
  headers: Headers
}
export type updateCategoryResponseError = (
  | updateCategoryResponse401
  | updateCategoryResponse403
) & {
  headers: Headers
}

export type updateCategoryResponse =
  | updateCategoryResponseSuccess
  | updateCategoryResponseError

export const getUpdateCategoryUrl = (id: string) => {
  return `/categories/${id}`
}

export const updateCategory = async (
  id: string,
  updateCategoryDto: UpdateCategoryDto,
  options?: RequestInit
): Promise<updateCategoryResponse> => {
  return customInstance<updateCategoryResponse>(getUpdateCategoryUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCategoryDto)
  })
}

export const getUpdateCategoryMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCategory>>,
    TError,
    { id: string; data: UpdateCategoryDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCategory>>,
  TError,
  { id: string; data: UpdateCategoryDto },
  TContext
> => {
  const mutationKey = ['updateCategory']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCategory>>,
    { id: string; data: UpdateCategoryDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateCategory(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCategory>>
>
export type UpdateCategoryMutationBody = UpdateCategoryDto
export type UpdateCategoryMutationError = ErrorType<void>

/**
 * @summary Update a category
 */
export const useUpdateCategory = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCategory>>,
      TError,
      { id: string; data: UpdateCategoryDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateCategory>>,
  TError,
  { id: string; data: UpdateCategoryDto },
  TContext
> => {
  return useMutation(getUpdateCategoryMutationOptions(options), queryClient)
}
/**
 * @summary Delete a category
 */
export type deleteCategoryResponse204 = {
  data: Category
  status: 204
}

export type deleteCategoryResponse401 = {
  data: void
  status: 401
}

export type deleteCategoryResponse403 = {
  data: void
  status: 403
}

export type deleteCategoryResponseSuccess = deleteCategoryResponse204 & {
  headers: Headers
}
export type deleteCategoryResponseError = (
  | deleteCategoryResponse401
  | deleteCategoryResponse403
) & {
  headers: Headers
}

export type deleteCategoryResponse =
  | deleteCategoryResponseSuccess
  | deleteCategoryResponseError

export const getDeleteCategoryUrl = (id: string) => {
  return `/categories/${id}`
}

export const deleteCategory = async (
  id: string,
  options?: RequestInit
): Promise<deleteCategoryResponse> => {
  return customInstance<deleteCategoryResponse>(getDeleteCategoryUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

export const getDeleteCategoryMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCategory>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteCategory']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCategory>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteCategory(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteCategoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCategory>>
>

export type DeleteCategoryMutationError = ErrorType<void>

/**
 * @summary Delete a category
 */
export const useDeleteCategory = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCategory>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCategory>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteCategoryMutationOptions(options), queryClient)
}
/**
 * @summary Update the status of a category
 */
export type updateCategoryStatusResponse200 = {
  data: Category
  status: 200
}

export type updateCategoryStatusResponse401 = {
  data: void
  status: 401
}

export type updateCategoryStatusResponse403 = {
  data: void
  status: 403
}

export type updateCategoryStatusResponseSuccess =
  updateCategoryStatusResponse200 & {
    headers: Headers
  }
export type updateCategoryStatusResponseError = (
  | updateCategoryStatusResponse401
  | updateCategoryStatusResponse403
) & {
  headers: Headers
}

export type updateCategoryStatusResponse =
  | updateCategoryStatusResponseSuccess
  | updateCategoryStatusResponseError

export const getUpdateCategoryStatusUrl = (id: string) => {
  return `/categories/${id}/status`
}

export const updateCategoryStatus = async (
  id: string,
  updateCategoryDto: UpdateCategoryDto,
  options?: RequestInit
): Promise<updateCategoryStatusResponse> => {
  return customInstance<updateCategoryStatusResponse>(
    getUpdateCategoryStatusUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateCategoryDto)
    }
  )
}

export const getUpdateCategoryStatusMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCategoryStatus>>,
    TError,
    { id: string; data: UpdateCategoryDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCategoryStatus>>,
  TError,
  { id: string; data: UpdateCategoryDto },
  TContext
> => {
  const mutationKey = ['updateCategoryStatus']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCategoryStatus>>,
    { id: string; data: UpdateCategoryDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateCategoryStatus(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateCategoryStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCategoryStatus>>
>
export type UpdateCategoryStatusMutationBody = UpdateCategoryDto
export type UpdateCategoryStatusMutationError = ErrorType<void>

/**
 * @summary Update the status of a category
 */
export const useUpdateCategoryStatus = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCategoryStatus>>,
      TError,
      { id: string; data: UpdateCategoryDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateCategoryStatus>>,
  TError,
  { id: string; data: UpdateCategoryDto },
  TContext
> => {
  return useMutation(
    getUpdateCategoryStatusMutationOptions(options),
    queryClient
  )
}
