/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  CreateSaleDto,
  GetAvailableProductsToSellDto,
  GetSaleDto,
  MarkInstallmentPaidDto,
  Sale,
  UpdateSaleDto,
  UpdateSaleStatusDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Confirm a sale
 */
export type confirmSaleResponse204 = {
  data: void
  status: 204
}

export type confirmSaleResponseSuccess = confirmSaleResponse204 & {
  headers: Headers
}
export type confirmSaleResponse = confirmSaleResponseSuccess

export const getConfirmSaleUrl = (id: string) => {
  return `/sales/${id}/confirm`
}

export const confirmSale = async (
  id: string,
  options?: RequestInit
): Promise<confirmSaleResponse> => {
  return customInstance<confirmSaleResponse>(getConfirmSaleUrl(id), {
    ...options,
    method: 'PATCH'
  })
}

export const getConfirmSaleMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof confirmSale>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof confirmSale>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['confirmSale']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof confirmSale>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return confirmSale(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ConfirmSaleMutationResult = NonNullable<
  Awaited<ReturnType<typeof confirmSale>>
>

export type ConfirmSaleMutationError = ErrorType<unknown>

/**
 * @summary Confirm a sale
 */
export const useConfirmSale = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof confirmSale>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof confirmSale>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getConfirmSaleMutationOptions(options), queryClient)
}
/**
 * @summary Get all sales
 */
export type getAllSalesResponse200 = {
  data: GetSaleDto[]
  status: 200
}

export type getAllSalesResponse401 = {
  data: void
  status: 401
}

export type getAllSalesResponse403 = {
  data: void
  status: 403
}

export type getAllSalesResponseSuccess = getAllSalesResponse200 & {
  headers: Headers
}
export type getAllSalesResponseError = (
  | getAllSalesResponse401
  | getAllSalesResponse403
) & {
  headers: Headers
}

export type getAllSalesResponse =
  | getAllSalesResponseSuccess
  | getAllSalesResponseError

export const getGetAllSalesUrl = () => {
  return `/sales`
}

export const getAllSales = async (
  options?: RequestInit
): Promise<getAllSalesResponse> => {
  return customInstance<getAllSalesResponse>(getGetAllSalesUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllSalesQueryKey = () => {
  return [`/sales`] as const
}

export const getGetAllSalesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllSales>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllSales>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllSalesQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSales>>> = ({
    signal
  }) => getAllSales({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllSales>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllSalesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllSales>>
>
export type GetAllSalesQueryError = ErrorType<void>

export function useGetAllSales<
  TData = Awaited<ReturnType<typeof getAllSales>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllSales>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSales>>,
          TError,
          Awaited<ReturnType<typeof getAllSales>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllSales<
  TData = Awaited<ReturnType<typeof getAllSales>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllSales>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSales>>,
          TError,
          Awaited<ReturnType<typeof getAllSales>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllSales<
  TData = Awaited<ReturnType<typeof getAllSales>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllSales>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all sales
 */

export function useGetAllSales<
  TData = Awaited<ReturnType<typeof getAllSales>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllSales>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllSalesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Create a new sale
 */
export type createSaleResponse201 = {
  data: Sale
  status: 201
}

export type createSaleResponse401 = {
  data: void
  status: 401
}

export type createSaleResponse403 = {
  data: void
  status: 403
}

export type createSaleResponseSuccess = createSaleResponse201 & {
  headers: Headers
}
export type createSaleResponseError = (
  | createSaleResponse401
  | createSaleResponse403
) & {
  headers: Headers
}

export type createSaleResponse =
  | createSaleResponseSuccess
  | createSaleResponseError

export const getCreateSaleUrl = () => {
  return `/sales`
}

export const createSale = async (
  createSaleDto: CreateSaleDto,
  options?: RequestInit
): Promise<createSaleResponse> => {
  return customInstance<createSaleResponse>(getCreateSaleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSaleDto)
  })
}

export const getCreateSaleMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSale>>,
    TError,
    { data: CreateSaleDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSale>>,
  TError,
  { data: CreateSaleDto },
  TContext
> => {
  const mutationKey = ['createSale']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSale>>,
    { data: CreateSaleDto }
  > = (props) => {
    const { data } = props ?? {}

    return createSale(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateSaleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSale>>
>
export type CreateSaleMutationBody = CreateSaleDto
export type CreateSaleMutationError = ErrorType<void>

/**
 * @summary Create a new sale
 */
export const useCreateSale = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSale>>,
      TError,
      { data: CreateSaleDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createSale>>,
  TError,
  { data: CreateSaleDto },
  TContext
> => {
  return useMutation(getCreateSaleMutationOptions(options), queryClient)
}
/**
 * @summary Get available products to sell
 */
export type getAvailableProductsToSellResponse200 = {
  data: GetAvailableProductsToSellDto
  status: 200
}

export type getAvailableProductsToSellResponse401 = {
  data: void
  status: 401
}

export type getAvailableProductsToSellResponse403 = {
  data: void
  status: 403
}

export type getAvailableProductsToSellResponseSuccess =
  getAvailableProductsToSellResponse200 & {
    headers: Headers
  }
export type getAvailableProductsToSellResponseError = (
  | getAvailableProductsToSellResponse401
  | getAvailableProductsToSellResponse403
) & {
  headers: Headers
}

export type getAvailableProductsToSellResponse =
  | getAvailableProductsToSellResponseSuccess
  | getAvailableProductsToSellResponseError

export const getGetAvailableProductsToSellUrl = () => {
  return `/sales/available-products`
}

export const getAvailableProductsToSell = async (
  options?: RequestInit
): Promise<getAvailableProductsToSellResponse> => {
  return customInstance<getAvailableProductsToSellResponse>(
    getGetAvailableProductsToSellUrl(),
    {
      ...options,
      method: 'GET'
    }
  )
}

export const getGetAvailableProductsToSellQueryKey = () => {
  return [`/sales/available-products`] as const
}

export const getGetAvailableProductsToSellQueryOptions = <
  TData = Awaited<ReturnType<typeof getAvailableProductsToSell>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAvailableProductsToSell>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetAvailableProductsToSellQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAvailableProductsToSell>>
  > = ({ signal }) => getAvailableProductsToSell({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAvailableProductsToSell>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvailableProductsToSellQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAvailableProductsToSell>>
>
export type GetAvailableProductsToSellQueryError = ErrorType<void>

export function useGetAvailableProductsToSell<
  TData = Awaited<ReturnType<typeof getAvailableProductsToSell>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableProductsToSell>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailableProductsToSell>>,
          TError,
          Awaited<ReturnType<typeof getAvailableProductsToSell>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAvailableProductsToSell<
  TData = Awaited<ReturnType<typeof getAvailableProductsToSell>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableProductsToSell>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAvailableProductsToSell>>,
          TError,
          Awaited<ReturnType<typeof getAvailableProductsToSell>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAvailableProductsToSell<
  TData = Awaited<ReturnType<typeof getAvailableProductsToSell>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableProductsToSell>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get available products to sell
 */

export function useGetAvailableProductsToSell<
  TData = Awaited<ReturnType<typeof getAvailableProductsToSell>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAvailableProductsToSell>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAvailableProductsToSellQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a specific sale
 */
export type getOneSaleResponse200 = {
  data: GetSaleDto
  status: 200
}

export type getOneSaleResponse401 = {
  data: void
  status: 401
}

export type getOneSaleResponse403 = {
  data: void
  status: 403
}

export type getOneSaleResponse404 = {
  data: void
  status: 404
}

export type getOneSaleResponseSuccess = getOneSaleResponse200 & {
  headers: Headers
}
export type getOneSaleResponseError = (
  | getOneSaleResponse401
  | getOneSaleResponse403
  | getOneSaleResponse404
) & {
  headers: Headers
}

export type getOneSaleResponse =
  | getOneSaleResponseSuccess
  | getOneSaleResponseError

export const getGetOneSaleUrl = (id: string) => {
  return `/sales/${id}`
}

export const getOneSale = async (
  id: string,
  options?: RequestInit
): Promise<getOneSaleResponse> => {
  return customInstance<getOneSaleResponse>(getGetOneSaleUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneSaleQueryKey = (id: string) => {
  return [`/sales/${id}`] as const
}

export const getGetOneSaleQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneSale>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSale>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneSaleQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneSale>>> = ({
    signal
  }) => getOneSale(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneSale>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneSaleQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneSale>>
>
export type GetOneSaleQueryError = ErrorType<void>

export function useGetOneSale<
  TData = Awaited<ReturnType<typeof getOneSale>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSale>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneSale>>,
          TError,
          Awaited<ReturnType<typeof getOneSale>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneSale<
  TData = Awaited<ReturnType<typeof getOneSale>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSale>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneSale>>,
          TError,
          Awaited<ReturnType<typeof getOneSale>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneSale<
  TData = Awaited<ReturnType<typeof getOneSale>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSale>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific sale
 */

export function useGetOneSale<
  TData = Awaited<ReturnType<typeof getOneSale>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneSale>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneSaleQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a sale
 */
export type updateSaleResponse200 = {
  data: Sale
  status: 200
}

export type updateSaleResponse401 = {
  data: void
  status: 401
}

export type updateSaleResponse403 = {
  data: void
  status: 403
}

export type updateSaleResponseSuccess = updateSaleResponse200 & {
  headers: Headers
}
export type updateSaleResponseError = (
  | updateSaleResponse401
  | updateSaleResponse403
) & {
  headers: Headers
}

export type updateSaleResponse =
  | updateSaleResponseSuccess
  | updateSaleResponseError

export const getUpdateSaleUrl = (id: string) => {
  return `/sales/${id}`
}

export const updateSale = async (
  id: string,
  updateSaleDto: UpdateSaleDto,
  options?: RequestInit
): Promise<updateSaleResponse> => {
  return customInstance<updateSaleResponse>(getUpdateSaleUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSaleDto)
  })
}

export const getUpdateSaleMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSale>>,
    TError,
    { id: string; data: UpdateSaleDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSale>>,
  TError,
  { id: string; data: UpdateSaleDto },
  TContext
> => {
  const mutationKey = ['updateSale']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSale>>,
    { id: string; data: UpdateSaleDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateSale(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateSaleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSale>>
>
export type UpdateSaleMutationBody = UpdateSaleDto
export type UpdateSaleMutationError = ErrorType<void>

/**
 * @summary Update a sale
 */
export const useUpdateSale = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSale>>,
      TError,
      { id: string; data: UpdateSaleDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateSale>>,
  TError,
  { id: string; data: UpdateSaleDto },
  TContext
> => {
  return useMutation(getUpdateSaleMutationOptions(options), queryClient)
}
/**
 * @summary Delete a sale
 */
export type deleteSaleResponse204 = {
  data: void
  status: 204
}

export type deleteSaleResponse401 = {
  data: void
  status: 401
}

export type deleteSaleResponse403 = {
  data: void
  status: 403
}

export type deleteSaleResponseSuccess = deleteSaleResponse204 & {
  headers: Headers
}
export type deleteSaleResponseError = (
  | deleteSaleResponse401
  | deleteSaleResponse403
) & {
  headers: Headers
}

export type deleteSaleResponse =
  | deleteSaleResponseSuccess
  | deleteSaleResponseError

export const getDeleteSaleUrl = (id: string) => {
  return `/sales/${id}`
}

export const deleteSale = async (
  id: string,
  options?: RequestInit
): Promise<deleteSaleResponse> => {
  return customInstance<deleteSaleResponse>(getDeleteSaleUrl(id), {
    ...options,
    method: 'DELETE'
  })
}

export const getDeleteSaleMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSale>>,
    TError,
    { id: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSale>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteSale']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSale>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {}

    return deleteSale(id, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteSaleMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteSale>>
>

export type DeleteSaleMutationError = ErrorType<void>

/**
 * @summary Delete a sale
 */
export const useDeleteSale = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSale>>,
      TError,
      { id: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSale>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteSaleMutationOptions(options), queryClient)
}
/**
 * @summary Mark installment as paid
 */
export type markInstallmentPaidResponse200 = {
  data: Sale
  status: 200
}

export type markInstallmentPaidResponse401 = {
  data: void
  status: 401
}

export type markInstallmentPaidResponse403 = {
  data: void
  status: 403
}

export type markInstallmentPaidResponseSuccess =
  markInstallmentPaidResponse200 & {
    headers: Headers
  }
export type markInstallmentPaidResponseError = (
  | markInstallmentPaidResponse401
  | markInstallmentPaidResponse403
) & {
  headers: Headers
}

export type markInstallmentPaidResponse =
  | markInstallmentPaidResponseSuccess
  | markInstallmentPaidResponseError

export const getMarkInstallmentPaidUrl = (id: string) => {
  return `/sales/${id}/installments/mark-paid`
}

export const markInstallmentPaid = async (
  id: string,
  markInstallmentPaidDto: MarkInstallmentPaidDto,
  options?: RequestInit
): Promise<markInstallmentPaidResponse> => {
  return customInstance<markInstallmentPaidResponse>(
    getMarkInstallmentPaidUrl(id),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(markInstallmentPaidDto)
    }
  )
}

export const getMarkInstallmentPaidMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markInstallmentPaid>>,
    TError,
    { id: string; data: MarkInstallmentPaidDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof markInstallmentPaid>>,
  TError,
  { id: string; data: MarkInstallmentPaidDto },
  TContext
> => {
  const mutationKey = ['markInstallmentPaid']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markInstallmentPaid>>,
    { id: string; data: MarkInstallmentPaidDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return markInstallmentPaid(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MarkInstallmentPaidMutationResult = NonNullable<
  Awaited<ReturnType<typeof markInstallmentPaid>>
>
export type MarkInstallmentPaidMutationBody = MarkInstallmentPaidDto
export type MarkInstallmentPaidMutationError = ErrorType<void>

/**
 * @summary Mark installment as paid
 */
export const useMarkInstallmentPaid = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof markInstallmentPaid>>,
      TError,
      { id: string; data: MarkInstallmentPaidDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof markInstallmentPaid>>,
  TError,
  { id: string; data: MarkInstallmentPaidDto },
  TContext
> => {
  return useMutation(
    getMarkInstallmentPaidMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Update sale status
 */
export type updateSaleStatusResponse200 = {
  data: Sale
  status: 200
}

export type updateSaleStatusResponse401 = {
  data: void
  status: 401
}

export type updateSaleStatusResponse403 = {
  data: void
  status: 403
}

export type updateSaleStatusResponseSuccess = updateSaleStatusResponse200 & {
  headers: Headers
}
export type updateSaleStatusResponseError = (
  | updateSaleStatusResponse401
  | updateSaleStatusResponse403
) & {
  headers: Headers
}

export type updateSaleStatusResponse =
  | updateSaleStatusResponseSuccess
  | updateSaleStatusResponseError

export const getUpdateSaleStatusUrl = (id: string) => {
  return `/sales/${id}/status`
}

export const updateSaleStatus = async (
  id: string,
  updateSaleStatusDto: UpdateSaleStatusDto,
  options?: RequestInit
): Promise<updateSaleStatusResponse> => {
  return customInstance<updateSaleStatusResponse>(getUpdateSaleStatusUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSaleStatusDto)
  })
}

export const getUpdateSaleStatusMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSaleStatus>>,
    TError,
    { id: string; data: UpdateSaleStatusDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSaleStatus>>,
  TError,
  { id: string; data: UpdateSaleStatusDto },
  TContext
> => {
  const mutationKey = ['updateSaleStatus']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSaleStatus>>,
    { id: string; data: UpdateSaleStatusDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateSaleStatus(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateSaleStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSaleStatus>>
>
export type UpdateSaleStatusMutationBody = UpdateSaleStatusDto
export type UpdateSaleStatusMutationError = ErrorType<void>

/**
 * @summary Update sale status
 */
export const useUpdateSaleStatus = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSaleStatus>>,
      TError,
      { id: string; data: UpdateSaleStatusDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateSaleStatus>>,
  TError,
  { id: string; data: UpdateSaleStatusDto },
  TContext
> => {
  return useMutation(getUpdateSaleStatusMutationOptions(options), queryClient)
}
