/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  CreateCustomerDto,
  Customer,
  TransferCustomerDto,
  UpdateCustomerDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Create a new customer
 */
export type createCustomerResponse201 = {
  data: Customer
  status: 201
}

export type createCustomerResponse401 = {
  data: void
  status: 401
}

export type createCustomerResponse403 = {
  data: void
  status: 403
}

export type createCustomerResponseSuccess = createCustomerResponse201 & {
  headers: Headers
}
export type createCustomerResponseError = (
  | createCustomerResponse401
  | createCustomerResponse403
) & {
  headers: Headers
}

export type createCustomerResponse =
  | createCustomerResponseSuccess
  | createCustomerResponseError

export const getCreateCustomerUrl = () => {
  return `/customers`
}

export const createCustomer = async (
  createCustomerDto: CreateCustomerDto,
  options?: RequestInit
): Promise<createCustomerResponse> => {
  return customInstance<createCustomerResponse>(getCreateCustomerUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCustomerDto)
  })
}

export const getCreateCustomerMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCustomer>>,
    TError,
    { data: CreateCustomerDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCustomer>>,
  TError,
  { data: CreateCustomerDto },
  TContext
> => {
  const mutationKey = ['createCustomer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCustomer>>,
    { data: CreateCustomerDto }
  > = (props) => {
    const { data } = props ?? {}

    return createCustomer(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateCustomerMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCustomer>>
>
export type CreateCustomerMutationBody = CreateCustomerDto
export type CreateCustomerMutationError = ErrorType<void>

/**
 * @summary Create a new customer
 */
export const useCreateCustomer = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCustomer>>,
      TError,
      { data: CreateCustomerDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createCustomer>>,
  TError,
  { data: CreateCustomerDto },
  TContext
> => {
  return useMutation(getCreateCustomerMutationOptions(options), queryClient)
}
/**
 * @summary Get all customers
 */
export type getAllCustomersResponse200 = {
  data: Customer[]
  status: 200
}

export type getAllCustomersResponse401 = {
  data: void
  status: 401
}

export type getAllCustomersResponse403 = {
  data: void
  status: 403
}

export type getAllCustomersResponseSuccess = getAllCustomersResponse200 & {
  headers: Headers
}
export type getAllCustomersResponseError = (
  | getAllCustomersResponse401
  | getAllCustomersResponse403
) & {
  headers: Headers
}

export type getAllCustomersResponse =
  | getAllCustomersResponseSuccess
  | getAllCustomersResponseError

export const getGetAllCustomersUrl = () => {
  return `/customers`
}

export const getAllCustomers = async (
  options?: RequestInit
): Promise<getAllCustomersResponse> => {
  return customInstance<getAllCustomersResponse>(getGetAllCustomersUrl(), {
    ...options,
    method: 'GET'
  })
}

export const getGetAllCustomersQueryKey = () => {
  return [`/customers`] as const
}

export const getGetAllCustomersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllCustomers>>,
  TError = ErrorType<void>
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllCustomers>>, TError, TData>
  >
  request?: SecondParameter<typeof customInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllCustomersQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCustomers>>> = ({
    signal
  }) => getAllCustomers({ signal, ...requestOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllCustomers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllCustomersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllCustomers>>
>
export type GetAllCustomersQueryError = ErrorType<void>

export function useGetAllCustomers<
  TData = Awaited<ReturnType<typeof getAllCustomers>>,
  TError = ErrorType<void>
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCustomers>>,
          TError,
          Awaited<ReturnType<typeof getAllCustomers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllCustomers<
  TData = Awaited<ReturnType<typeof getAllCustomers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCustomers>>,
          TError,
          Awaited<ReturnType<typeof getAllCustomers>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllCustomers<
  TData = Awaited<ReturnType<typeof getAllCustomers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all customers
 */

export function useGetAllCustomers<
  TData = Awaited<ReturnType<typeof getAllCustomers>>,
  TError = ErrorType<void>
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomers>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetAllCustomersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get a specific customer
 */
export type getOneCustomerResponse200 = {
  data: Customer
  status: 200
}

export type getOneCustomerResponse401 = {
  data: void
  status: 401
}

export type getOneCustomerResponse403 = {
  data: void
  status: 403
}

export type getOneCustomerResponse404 = {
  data: void
  status: 404
}

export type getOneCustomerResponseSuccess = getOneCustomerResponse200 & {
  headers: Headers
}
export type getOneCustomerResponseError = (
  | getOneCustomerResponse401
  | getOneCustomerResponse403
  | getOneCustomerResponse404
) & {
  headers: Headers
}

export type getOneCustomerResponse =
  | getOneCustomerResponseSuccess
  | getOneCustomerResponseError

export const getGetOneCustomerUrl = (id: string) => {
  return `/customers/${id}`
}

export const getOneCustomer = async (
  id: string,
  options?: RequestInit
): Promise<getOneCustomerResponse> => {
  return customInstance<getOneCustomerResponse>(getGetOneCustomerUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetOneCustomerQueryKey = (id: string) => {
  return [`/customers/${id}`] as const
}

export const getGetOneCustomerQueryOptions = <
  TData = Awaited<ReturnType<typeof getOneCustomer>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCustomer>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetOneCustomerQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneCustomer>>> = ({
    signal
  }) => getOneCustomer(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOneCustomer>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneCustomerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOneCustomer>>
>
export type GetOneCustomerQueryError = ErrorType<void>

export function useGetOneCustomer<
  TData = Awaited<ReturnType<typeof getOneCustomer>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCustomer>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneCustomer>>,
          TError,
          Awaited<ReturnType<typeof getOneCustomer>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneCustomer<
  TData = Awaited<ReturnType<typeof getOneCustomer>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCustomer>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOneCustomer>>,
          TError,
          Awaited<ReturnType<typeof getOneCustomer>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOneCustomer<
  TData = Awaited<ReturnType<typeof getOneCustomer>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCustomer>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get a specific customer
 */

export function useGetOneCustomer<
  TData = Awaited<ReturnType<typeof getOneCustomer>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOneCustomer>>, TError, TData>
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOneCustomerQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Update a customer
 */
export type updateCustomerResponse200 = {
  data: Customer
  status: 200
}

export type updateCustomerResponse401 = {
  data: void
  status: 401
}

export type updateCustomerResponse403 = {
  data: void
  status: 403
}

export type updateCustomerResponseSuccess = updateCustomerResponse200 & {
  headers: Headers
}
export type updateCustomerResponseError = (
  | updateCustomerResponse401
  | updateCustomerResponse403
) & {
  headers: Headers
}

export type updateCustomerResponse =
  | updateCustomerResponseSuccess
  | updateCustomerResponseError

export const getUpdateCustomerUrl = (id: string) => {
  return `/customers/${id}`
}

export const updateCustomer = async (
  id: string,
  updateCustomerDto: UpdateCustomerDto,
  options?: RequestInit
): Promise<updateCustomerResponse> => {
  return customInstance<updateCustomerResponse>(getUpdateCustomerUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCustomerDto)
  })
}

export const getUpdateCustomerMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCustomer>>,
    TError,
    { id: string; data: UpdateCustomerDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCustomer>>,
  TError,
  { id: string; data: UpdateCustomerDto },
  TContext
> => {
  const mutationKey = ['updateCustomer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCustomer>>,
    { id: string; data: UpdateCustomerDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return updateCustomer(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateCustomerMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCustomer>>
>
export type UpdateCustomerMutationBody = UpdateCustomerDto
export type UpdateCustomerMutationError = ErrorType<void>

/**
 * @summary Update a customer
 */
export const useUpdateCustomer = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCustomer>>,
      TError,
      { id: string; data: UpdateCustomerDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateCustomer>>,
  TError,
  { id: string; data: UpdateCustomerDto },
  TContext
> => {
  return useMutation(getUpdateCustomerMutationOptions(options), queryClient)
}
/**
 * @summary Delete a customer
 */
export type deleteCustomerResponse204 = {
  data: void
  status: 204
}

export type deleteCustomerResponse401 = {
  data: void
  status: 401
}

export type deleteCustomerResponse403 = {
  data: void
  status: 403
}

export type deleteCustomerResponseSuccess = deleteCustomerResponse204 & {
  headers: Headers
}
export type deleteCustomerResponseError = (
  | deleteCustomerResponse401
  | deleteCustomerResponse403
) & {
  headers: Headers
}

export type deleteCustomerResponse =
  | deleteCustomerResponseSuccess
  | deleteCustomerResponseError

export const getDeleteCustomerUrl = (id: string, fromResellerId: string) => {
  return `/customers/${id}/from/${fromResellerId}`
}

export const deleteCustomer = async (
  id: string,
  fromResellerId: string,
  options?: RequestInit
): Promise<deleteCustomerResponse> => {
  return customInstance<deleteCustomerResponse>(
    getDeleteCustomerUrl(id, fromResellerId),
    {
      ...options,
      method: 'DELETE'
    }
  )
}

export const getDeleteCustomerMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCustomer>>,
    TError,
    { id: string; fromResellerId: string },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCustomer>>,
  TError,
  { id: string; fromResellerId: string },
  TContext
> => {
  const mutationKey = ['deleteCustomer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCustomer>>,
    { id: string; fromResellerId: string }
  > = (props) => {
    const { id, fromResellerId } = props ?? {}

    return deleteCustomer(id, fromResellerId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteCustomerMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCustomer>>
>

export type DeleteCustomerMutationError = ErrorType<void>

/**
 * @summary Delete a customer
 */
export const useDeleteCustomer = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCustomer>>,
      TError,
      { id: string; fromResellerId: string },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCustomer>>,
  TError,
  { id: string; fromResellerId: string },
  TContext
> => {
  return useMutation(getDeleteCustomerMutationOptions(options), queryClient)
}
/**
 * @summary Transfer a customer
 */
export type transferCustomerResponse204 = {
  data: void
  status: 204
}

export type transferCustomerResponse401 = {
  data: void
  status: 401
}

export type transferCustomerResponse403 = {
  data: void
  status: 403
}

export type transferCustomerResponseSuccess = transferCustomerResponse204 & {
  headers: Headers
}
export type transferCustomerResponseError = (
  | transferCustomerResponse401
  | transferCustomerResponse403
) & {
  headers: Headers
}

export type transferCustomerResponse =
  | transferCustomerResponseSuccess
  | transferCustomerResponseError

export const getTransferCustomerUrl = (id: string) => {
  return `/customers/${id}/transfer`
}

export const transferCustomer = async (
  id: string,
  transferCustomerDto: TransferCustomerDto,
  options?: RequestInit
): Promise<transferCustomerResponse> => {
  return customInstance<transferCustomerResponse>(getTransferCustomerUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(transferCustomerDto)
  })
}

export const getTransferCustomerMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof transferCustomer>>,
    TError,
    { id: string; data: TransferCustomerDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof transferCustomer>>,
  TError,
  { id: string; data: TransferCustomerDto },
  TContext
> => {
  const mutationKey = ['transferCustomer']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof transferCustomer>>,
    { id: string; data: TransferCustomerDto }
  > = (props) => {
    const { id, data } = props ?? {}

    return transferCustomer(id, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type TransferCustomerMutationResult = NonNullable<
  Awaited<ReturnType<typeof transferCustomer>>
>
export type TransferCustomerMutationBody = TransferCustomerDto
export type TransferCustomerMutationError = ErrorType<void>

/**
 * @summary Transfer a customer
 */
export const useTransferCustomer = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof transferCustomer>>,
      TError,
      { id: string; data: TransferCustomerDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof transferCustomer>>,
  TError,
  { id: string; data: TransferCustomerDto },
  TContext
> => {
  return useMutation(getTransferCustomerMutationOptions(options), queryClient)
}
