export enum SaleStatus {
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  INSTALLMENTS_PENDING = 'INSTALLMENTS_PENDING',
  INSTALLMENTS_PAID = 'INSTALLMENTS_PAID',
  INSTALLMENTS_OVERDUE = 'INSTALLMENTS_OVERDUE'
}
