/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type {
  GetOwnershipTransfersByResellerId200,
  GetOwnershipTransfersByResellerIdParams,
  GetOwnershipTransfersGivenByResellerId200,
  GetOwnershipTransfersGivenByResellerIdParams,
  GetOwnershipTransfersInPeriod200,
  GetOwnershipTransfersInPeriodParams,
  GetOwnershipTransfersReceivedByResellerId200,
  GetOwnershipTransfersReceivedByResellerIdParams,
  GetTotalOwnershipTransfersByResellerIdParams,
  GetTotalOwnershipTransfersGivenByResellerIdParams,
  GetTotalOwnershipTransfersInPeriodParams,
  GetTotalOwnershipTransfersReceivedByResellerIdParams,
  ParamsDto,
  ParamsWithMandatoryPeriodDto
} from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get Ownership Transfers By Reseller Id
 */
export type getOwnershipTransfersByResellerIdResponse200 = {
  data: GetOwnershipTransfersByResellerId200
  status: 200
}

export type getOwnershipTransfersByResellerIdResponse401 = {
  data: void
  status: 401
}

export type getOwnershipTransfersByResellerIdResponse403 = {
  data: void
  status: 403
}

export type getOwnershipTransfersByResellerIdResponseSuccess =
  getOwnershipTransfersByResellerIdResponse200 & {
    headers: Headers
  }
export type getOwnershipTransfersByResellerIdResponseError = (
  | getOwnershipTransfersByResellerIdResponse401
  | getOwnershipTransfersByResellerIdResponse403
) & {
  headers: Headers
}

export type getOwnershipTransfersByResellerIdResponse =
  | getOwnershipTransfersByResellerIdResponseSuccess
  | getOwnershipTransfersByResellerIdResponseError

export const getGetOwnershipTransfersByResellerIdUrl = (
  id: string,
  params?: GetOwnershipTransfersByResellerIdParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/kpi/admin/ownership-transfers/by-reseller/${id}?${stringifiedParams}`
    : `/kpi/admin/ownership-transfers/by-reseller/${id}`
}

export const getOwnershipTransfersByResellerId = async (
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersByResellerIdParams,
  options?: RequestInit
): Promise<getOwnershipTransfersByResellerIdResponse> => {
  return customInstance<getOwnershipTransfersByResellerIdResponse>(
    getGetOwnershipTransfersByResellerIdUrl(id, params),
    {
      ...options,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getGetOwnershipTransfersByResellerIdQueryKey = (
  id: string,
  paramsDto?: ParamsDto,
  params?: GetOwnershipTransfersByResellerIdParams
) => {
  return [
    `/kpi/admin/ownership-transfers/by-reseller/${id}`,
    ...(params ? [params] : []),
    paramsDto
  ] as const
}

export const getGetOwnershipTransfersByResellerIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetOwnershipTransfersByResellerIdQueryKey(id, paramsDto, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>
  > = ({ signal }) =>
    getOwnershipTransfersByResellerId(id, paramsDto, params, {
      signal,
      ...requestOptions
    })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOwnershipTransfersByResellerIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>
>
export type GetOwnershipTransfersByResellerIdQueryError = ErrorType<void>

export function useGetOwnershipTransfersByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params: undefined | GetOwnershipTransfersByResellerIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
          TError,
          Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOwnershipTransfersByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
          TError,
          Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOwnershipTransfersByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Ownership Transfers By Reseller Id
 */

export function useGetOwnershipTransfersByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOwnershipTransfersByResellerIdQueryOptions(
    id,
    paramsDto,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get Total Ownership Transfers By Reseller Id
 */
export type getTotalOwnershipTransfersByResellerIdResponse200 = {
  data: number
  status: 200
}

export type getTotalOwnershipTransfersByResellerIdResponse401 = {
  data: void
  status: 401
}

export type getTotalOwnershipTransfersByResellerIdResponse403 = {
  data: void
  status: 403
}

export type getTotalOwnershipTransfersByResellerIdResponseSuccess =
  getTotalOwnershipTransfersByResellerIdResponse200 & {
    headers: Headers
  }
export type getTotalOwnershipTransfersByResellerIdResponseError = (
  | getTotalOwnershipTransfersByResellerIdResponse401
  | getTotalOwnershipTransfersByResellerIdResponse403
) & {
  headers: Headers
}

export type getTotalOwnershipTransfersByResellerIdResponse =
  | getTotalOwnershipTransfersByResellerIdResponseSuccess
  | getTotalOwnershipTransfersByResellerIdResponseError

export const getGetTotalOwnershipTransfersByResellerIdUrl = (
  id: string,
  params?: GetTotalOwnershipTransfersByResellerIdParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/kpi/admin/ownership-transfers/by-reseller/${id}/total?${stringifiedParams}`
    : `/kpi/admin/ownership-transfers/by-reseller/${id}/total`
}

export const getTotalOwnershipTransfersByResellerId = async (
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersByResellerIdParams,
  options?: RequestInit
): Promise<getTotalOwnershipTransfersByResellerIdResponse> => {
  return customInstance<getTotalOwnershipTransfersByResellerIdResponse>(
    getGetTotalOwnershipTransfersByResellerIdUrl(id, params),
    {
      ...options,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getGetTotalOwnershipTransfersByResellerIdQueryKey = (
  id: string,
  paramsDto?: ParamsDto,
  params?: GetTotalOwnershipTransfersByResellerIdParams
) => {
  return [
    `/kpi/admin/ownership-transfers/by-reseller/${id}/total`,
    ...(params ? [params] : []),
    paramsDto
  ] as const
}

export const getGetTotalOwnershipTransfersByResellerIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetTotalOwnershipTransfersByResellerIdQueryKey(id, paramsDto, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>
  > = ({ signal }) =>
    getTotalOwnershipTransfersByResellerId(id, paramsDto, params, {
      signal,
      ...requestOptions
    })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTotalOwnershipTransfersByResellerIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>
>
export type GetTotalOwnershipTransfersByResellerIdQueryError = ErrorType<void>

export function useGetTotalOwnershipTransfersByResellerId<
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params: undefined | GetTotalOwnershipTransfersByResellerIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
          TError,
          Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTotalOwnershipTransfersByResellerId<
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
          TError,
          Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTotalOwnershipTransfersByResellerId<
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Total Ownership Transfers By Reseller Id
 */

export function useGetTotalOwnershipTransfersByResellerId<
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetTotalOwnershipTransfersByResellerIdQueryOptions(
    id,
    paramsDto,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get Ownership Transfers In Period
 */
export type getOwnershipTransfersInPeriodResponse200 = {
  data: GetOwnershipTransfersInPeriod200
  status: 200
}

export type getOwnershipTransfersInPeriodResponse401 = {
  data: void
  status: 401
}

export type getOwnershipTransfersInPeriodResponse403 = {
  data: void
  status: 403
}

export type getOwnershipTransfersInPeriodResponseSuccess =
  getOwnershipTransfersInPeriodResponse200 & {
    headers: Headers
  }
export type getOwnershipTransfersInPeriodResponseError = (
  | getOwnershipTransfersInPeriodResponse401
  | getOwnershipTransfersInPeriodResponse403
) & {
  headers: Headers
}

export type getOwnershipTransfersInPeriodResponse =
  | getOwnershipTransfersInPeriodResponseSuccess
  | getOwnershipTransfersInPeriodResponseError

export const getGetOwnershipTransfersInPeriodUrl = (
  params: GetOwnershipTransfersInPeriodParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/kpi/admin/ownership-transfers/in-period?${stringifiedParams}`
    : `/kpi/admin/ownership-transfers/in-period`
}

export const getOwnershipTransfersInPeriod = async (
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetOwnershipTransfersInPeriodParams,
  options?: RequestInit
): Promise<getOwnershipTransfersInPeriodResponse> => {
  return customInstance<getOwnershipTransfersInPeriodResponse>(
    getGetOwnershipTransfersInPeriodUrl(params),
    {
      ...options,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsWithMandatoryPeriodDto)
    }
  )
}

export const getGetOwnershipTransfersInPeriodQueryKey = (
  paramsWithMandatoryPeriodDto?: ParamsWithMandatoryPeriodDto,
  params?: GetOwnershipTransfersInPeriodParams
) => {
  return [
    `/kpi/admin/ownership-transfers/in-period`,
    ...(params ? [params] : []),
    paramsWithMandatoryPeriodDto
  ] as const
}

export const getGetOwnershipTransfersInPeriodQueryOptions = <
  TData = Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetOwnershipTransfersInPeriodParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetOwnershipTransfersInPeriodQueryKey(
      paramsWithMandatoryPeriodDto,
      params
    )

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>
  > = ({ signal }) =>
    getOwnershipTransfersInPeriod(paramsWithMandatoryPeriodDto, params, {
      signal,
      ...requestOptions
    })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOwnershipTransfersInPeriodQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>
>
export type GetOwnershipTransfersInPeriodQueryError = ErrorType<void>

export function useGetOwnershipTransfersInPeriod<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetOwnershipTransfersInPeriodParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
          TError,
          Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOwnershipTransfersInPeriod<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetOwnershipTransfersInPeriodParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
          TError,
          Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOwnershipTransfersInPeriod<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetOwnershipTransfersInPeriodParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Ownership Transfers In Period
 */

export function useGetOwnershipTransfersInPeriod<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetOwnershipTransfersInPeriodParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOwnershipTransfersInPeriodQueryOptions(
    paramsWithMandatoryPeriodDto,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get Total Ownership Transfers In Period
 */
export type getTotalOwnershipTransfersInPeriodResponse200 = {
  data: number
  status: 200
}

export type getTotalOwnershipTransfersInPeriodResponse401 = {
  data: void
  status: 401
}

export type getTotalOwnershipTransfersInPeriodResponse403 = {
  data: void
  status: 403
}

export type getTotalOwnershipTransfersInPeriodResponseSuccess =
  getTotalOwnershipTransfersInPeriodResponse200 & {
    headers: Headers
  }
export type getTotalOwnershipTransfersInPeriodResponseError = (
  | getTotalOwnershipTransfersInPeriodResponse401
  | getTotalOwnershipTransfersInPeriodResponse403
) & {
  headers: Headers
}

export type getTotalOwnershipTransfersInPeriodResponse =
  | getTotalOwnershipTransfersInPeriodResponseSuccess
  | getTotalOwnershipTransfersInPeriodResponseError

export const getGetTotalOwnershipTransfersInPeriodUrl = (
  params: GetTotalOwnershipTransfersInPeriodParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/kpi/admin/ownership-transfers/in-period/total?${stringifiedParams}`
    : `/kpi/admin/ownership-transfers/in-period/total`
}

export const getTotalOwnershipTransfersInPeriod = async (
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetTotalOwnershipTransfersInPeriodParams,
  options?: RequestInit
): Promise<getTotalOwnershipTransfersInPeriodResponse> => {
  return customInstance<getTotalOwnershipTransfersInPeriodResponse>(
    getGetTotalOwnershipTransfersInPeriodUrl(params),
    {
      ...options,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsWithMandatoryPeriodDto)
    }
  )
}

export const getGetTotalOwnershipTransfersInPeriodQueryKey = (
  paramsWithMandatoryPeriodDto?: ParamsWithMandatoryPeriodDto,
  params?: GetTotalOwnershipTransfersInPeriodParams
) => {
  return [
    `/kpi/admin/ownership-transfers/in-period/total`,
    ...(params ? [params] : []),
    paramsWithMandatoryPeriodDto
  ] as const
}

export const getGetTotalOwnershipTransfersInPeriodQueryOptions = <
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetTotalOwnershipTransfersInPeriodParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetTotalOwnershipTransfersInPeriodQueryKey(
      paramsWithMandatoryPeriodDto,
      params
    )

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>
  > = ({ signal }) =>
    getTotalOwnershipTransfersInPeriod(paramsWithMandatoryPeriodDto, params, {
      signal,
      ...requestOptions
    })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTotalOwnershipTransfersInPeriodQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>
>
export type GetTotalOwnershipTransfersInPeriodQueryError = ErrorType<void>

export function useGetTotalOwnershipTransfersInPeriod<
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetTotalOwnershipTransfersInPeriodParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
          TError,
          Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTotalOwnershipTransfersInPeriod<
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetTotalOwnershipTransfersInPeriodParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
          TError,
          Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTotalOwnershipTransfersInPeriod<
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetTotalOwnershipTransfersInPeriodParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Total Ownership Transfers In Period
 */

export function useGetTotalOwnershipTransfersInPeriod<
  TData = Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
  TError = ErrorType<void>
>(
  paramsWithMandatoryPeriodDto: ParamsWithMandatoryPeriodDto,
  params: GetTotalOwnershipTransfersInPeriodParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersInPeriod>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetTotalOwnershipTransfersInPeriodQueryOptions(
    paramsWithMandatoryPeriodDto,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get Ownership Transfers Received By Reseller Id
 */
export type getOwnershipTransfersReceivedByResellerIdResponse200 = {
  data: GetOwnershipTransfersReceivedByResellerId200
  status: 200
}

export type getOwnershipTransfersReceivedByResellerIdResponse401 = {
  data: void
  status: 401
}

export type getOwnershipTransfersReceivedByResellerIdResponse403 = {
  data: void
  status: 403
}

export type getOwnershipTransfersReceivedByResellerIdResponseSuccess =
  getOwnershipTransfersReceivedByResellerIdResponse200 & {
    headers: Headers
  }
export type getOwnershipTransfersReceivedByResellerIdResponseError = (
  | getOwnershipTransfersReceivedByResellerIdResponse401
  | getOwnershipTransfersReceivedByResellerIdResponse403
) & {
  headers: Headers
}

export type getOwnershipTransfersReceivedByResellerIdResponse =
  | getOwnershipTransfersReceivedByResellerIdResponseSuccess
  | getOwnershipTransfersReceivedByResellerIdResponseError

export const getGetOwnershipTransfersReceivedByResellerIdUrl = (
  id: string,
  params?: GetOwnershipTransfersReceivedByResellerIdParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/kpi/admin/ownership-transfers/received/by-reseller/${id}?${stringifiedParams}`
    : `/kpi/admin/ownership-transfers/received/by-reseller/${id}`
}

export const getOwnershipTransfersReceivedByResellerId = async (
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersReceivedByResellerIdParams,
  options?: RequestInit
): Promise<getOwnershipTransfersReceivedByResellerIdResponse> => {
  return customInstance<getOwnershipTransfersReceivedByResellerIdResponse>(
    getGetOwnershipTransfersReceivedByResellerIdUrl(id, params),
    {
      ...options,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getGetOwnershipTransfersReceivedByResellerIdQueryKey = (
  id: string,
  paramsDto?: ParamsDto,
  params?: GetOwnershipTransfersReceivedByResellerIdParams
) => {
  return [
    `/kpi/admin/ownership-transfers/received/by-reseller/${id}`,
    ...(params ? [params] : []),
    paramsDto
  ] as const
}

export const getGetOwnershipTransfersReceivedByResellerIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersReceivedByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetOwnershipTransfersReceivedByResellerIdQueryKey(id, paramsDto, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>
  > = ({ signal }) =>
    getOwnershipTransfersReceivedByResellerId(id, paramsDto, params, {
      signal,
      ...requestOptions
    })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOwnershipTransfersReceivedByResellerIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>
>
export type GetOwnershipTransfersReceivedByResellerIdQueryError =
  ErrorType<void>

export function useGetOwnershipTransfersReceivedByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params: undefined | GetOwnershipTransfersReceivedByResellerIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
          TError,
          Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOwnershipTransfersReceivedByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersReceivedByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
          TError,
          Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOwnershipTransfersReceivedByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersReceivedByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Ownership Transfers Received By Reseller Id
 */

export function useGetOwnershipTransfersReceivedByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersReceivedByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersReceivedByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOwnershipTransfersReceivedByResellerIdQueryOptions(
    id,
    paramsDto,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get Total Ownership Transfers Received By Reseller Id
 */
export type getTotalOwnershipTransfersReceivedByResellerIdResponse200 = {
  data: number
  status: 200
}

export type getTotalOwnershipTransfersReceivedByResellerIdResponse401 = {
  data: void
  status: 401
}

export type getTotalOwnershipTransfersReceivedByResellerIdResponse403 = {
  data: void
  status: 403
}

export type getTotalOwnershipTransfersReceivedByResellerIdResponseSuccess =
  getTotalOwnershipTransfersReceivedByResellerIdResponse200 & {
    headers: Headers
  }
export type getTotalOwnershipTransfersReceivedByResellerIdResponseError = (
  | getTotalOwnershipTransfersReceivedByResellerIdResponse401
  | getTotalOwnershipTransfersReceivedByResellerIdResponse403
) & {
  headers: Headers
}

export type getTotalOwnershipTransfersReceivedByResellerIdResponse =
  | getTotalOwnershipTransfersReceivedByResellerIdResponseSuccess
  | getTotalOwnershipTransfersReceivedByResellerIdResponseError

export const getGetTotalOwnershipTransfersReceivedByResellerIdUrl = (
  id: string,
  params?: GetTotalOwnershipTransfersReceivedByResellerIdParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/kpi/admin/ownership-transfers/received/by-reseller/${id}/total?${stringifiedParams}`
    : `/kpi/admin/ownership-transfers/received/by-reseller/${id}/total`
}

export const getTotalOwnershipTransfersReceivedByResellerId = async (
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersReceivedByResellerIdParams,
  options?: RequestInit
): Promise<getTotalOwnershipTransfersReceivedByResellerIdResponse> => {
  return customInstance<getTotalOwnershipTransfersReceivedByResellerIdResponse>(
    getGetTotalOwnershipTransfersReceivedByResellerIdUrl(id, params),
    {
      ...options,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getGetTotalOwnershipTransfersReceivedByResellerIdQueryKey = (
  id: string,
  paramsDto?: ParamsDto,
  params?: GetTotalOwnershipTransfersReceivedByResellerIdParams
) => {
  return [
    `/kpi/admin/ownership-transfers/received/by-reseller/${id}/total`,
    ...(params ? [params] : []),
    paramsDto
  ] as const
}

export const getGetTotalOwnershipTransfersReceivedByResellerIdQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersReceivedByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
        >,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetTotalOwnershipTransfersReceivedByResellerIdQueryKey(
      id,
      paramsDto,
      params
    )

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>>
  > = ({ signal }) =>
    getTotalOwnershipTransfersReceivedByResellerId(id, paramsDto, params, {
      signal,
      ...requestOptions
    })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTotalOwnershipTransfersReceivedByResellerIdQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>>
  >
export type GetTotalOwnershipTransfersReceivedByResellerIdQueryError =
  ErrorType<void>

export function useGetTotalOwnershipTransfersReceivedByResellerId<
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params: undefined | GetTotalOwnershipTransfersReceivedByResellerIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
          >,
          TError,
          Awaited<
            ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
          >
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTotalOwnershipTransfersReceivedByResellerId<
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersReceivedByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
          >,
          TError,
          Awaited<
            ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
          >
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTotalOwnershipTransfersReceivedByResellerId<
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersReceivedByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
        >,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Total Ownership Transfers Received By Reseller Id
 */

export function useGetTotalOwnershipTransfersReceivedByResellerId<
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersReceivedByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getTotalOwnershipTransfersReceivedByResellerId>
        >,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions =
    getGetTotalOwnershipTransfersReceivedByResellerIdQueryOptions(
      id,
      paramsDto,
      params,
      options
    )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get Ownership Transfers Given By Reseller Id
 */
export type getOwnershipTransfersGivenByResellerIdResponse200 = {
  data: GetOwnershipTransfersGivenByResellerId200
  status: 200
}

export type getOwnershipTransfersGivenByResellerIdResponse401 = {
  data: void
  status: 401
}

export type getOwnershipTransfersGivenByResellerIdResponse403 = {
  data: void
  status: 403
}

export type getOwnershipTransfersGivenByResellerIdResponseSuccess =
  getOwnershipTransfersGivenByResellerIdResponse200 & {
    headers: Headers
  }
export type getOwnershipTransfersGivenByResellerIdResponseError = (
  | getOwnershipTransfersGivenByResellerIdResponse401
  | getOwnershipTransfersGivenByResellerIdResponse403
) & {
  headers: Headers
}

export type getOwnershipTransfersGivenByResellerIdResponse =
  | getOwnershipTransfersGivenByResellerIdResponseSuccess
  | getOwnershipTransfersGivenByResellerIdResponseError

export const getGetOwnershipTransfersGivenByResellerIdUrl = (
  id: string,
  params?: GetOwnershipTransfersGivenByResellerIdParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/kpi/admin/ownership-transfers/given/by-reseller/${id}?${stringifiedParams}`
    : `/kpi/admin/ownership-transfers/given/by-reseller/${id}`
}

export const getOwnershipTransfersGivenByResellerId = async (
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersGivenByResellerIdParams,
  options?: RequestInit
): Promise<getOwnershipTransfersGivenByResellerIdResponse> => {
  return customInstance<getOwnershipTransfersGivenByResellerIdResponse>(
    getGetOwnershipTransfersGivenByResellerIdUrl(id, params),
    {
      ...options,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getGetOwnershipTransfersGivenByResellerIdQueryKey = (
  id: string,
  paramsDto?: ParamsDto,
  params?: GetOwnershipTransfersGivenByResellerIdParams
) => {
  return [
    `/kpi/admin/ownership-transfers/given/by-reseller/${id}`,
    ...(params ? [params] : []),
    paramsDto
  ] as const
}

export const getGetOwnershipTransfersGivenByResellerIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersGivenByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetOwnershipTransfersGivenByResellerIdQueryKey(id, paramsDto, params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>
  > = ({ signal }) =>
    getOwnershipTransfersGivenByResellerId(id, paramsDto, params, {
      signal,
      ...requestOptions
    })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOwnershipTransfersGivenByResellerIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>
>
export type GetOwnershipTransfersGivenByResellerIdQueryError = ErrorType<void>

export function useGetOwnershipTransfersGivenByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params: undefined | GetOwnershipTransfersGivenByResellerIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
          TError,
          Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOwnershipTransfersGivenByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersGivenByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
          TError,
          Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetOwnershipTransfersGivenByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersGivenByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Ownership Transfers Given By Reseller Id
 */

export function useGetOwnershipTransfersGivenByResellerId<
  TData = Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetOwnershipTransfersGivenByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetOwnershipTransfersGivenByResellerIdQueryOptions(
    id,
    paramsDto,
    params,
    options
  )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * @summary Get Total Ownership Transfers Given By Reseller Id
 */
export type getTotalOwnershipTransfersGivenByResellerIdResponse200 = {
  data: number
  status: 200
}

export type getTotalOwnershipTransfersGivenByResellerIdResponse401 = {
  data: void
  status: 401
}

export type getTotalOwnershipTransfersGivenByResellerIdResponse403 = {
  data: void
  status: 403
}

export type getTotalOwnershipTransfersGivenByResellerIdResponseSuccess =
  getTotalOwnershipTransfersGivenByResellerIdResponse200 & {
    headers: Headers
  }
export type getTotalOwnershipTransfersGivenByResellerIdResponseError = (
  | getTotalOwnershipTransfersGivenByResellerIdResponse401
  | getTotalOwnershipTransfersGivenByResellerIdResponse403
) & {
  headers: Headers
}

export type getTotalOwnershipTransfersGivenByResellerIdResponse =
  | getTotalOwnershipTransfersGivenByResellerIdResponseSuccess
  | getTotalOwnershipTransfersGivenByResellerIdResponseError

export const getGetTotalOwnershipTransfersGivenByResellerIdUrl = (
  id: string,
  params?: GetTotalOwnershipTransfersGivenByResellerIdParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/kpi/admin/ownership-transfers/given/by-reseller/${id}/total?${stringifiedParams}`
    : `/kpi/admin/ownership-transfers/given/by-reseller/${id}/total`
}

export const getTotalOwnershipTransfersGivenByResellerId = async (
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersGivenByResellerIdParams,
  options?: RequestInit
): Promise<getTotalOwnershipTransfersGivenByResellerIdResponse> => {
  return customInstance<getTotalOwnershipTransfersGivenByResellerIdResponse>(
    getGetTotalOwnershipTransfersGivenByResellerIdUrl(id, params),
    {
      ...options,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getGetTotalOwnershipTransfersGivenByResellerIdQueryKey = (
  id: string,
  paramsDto?: ParamsDto,
  params?: GetTotalOwnershipTransfersGivenByResellerIdParams
) => {
  return [
    `/kpi/admin/ownership-transfers/given/by-reseller/${id}/total`,
    ...(params ? [params] : []),
    paramsDto
  ] as const
}

export const getGetTotalOwnershipTransfersGivenByResellerIdQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersGivenByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetTotalOwnershipTransfersGivenByResellerIdQueryKey(
      id,
      paramsDto,
      params
    )

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>>
  > = ({ signal }) =>
    getTotalOwnershipTransfersGivenByResellerId(id, paramsDto, params, {
      signal,
      ...requestOptions
    })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTotalOwnershipTransfersGivenByResellerIdQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>>
  >
export type GetTotalOwnershipTransfersGivenByResellerIdQueryError =
  ErrorType<void>

export function useGetTotalOwnershipTransfersGivenByResellerId<
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params: undefined | GetTotalOwnershipTransfersGivenByResellerIdParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
          >,
          TError,
          Awaited<
            ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
          >
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTotalOwnershipTransfersGivenByResellerId<
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersGivenByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
          >,
          TError,
          Awaited<
            ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
          >
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetTotalOwnershipTransfersGivenByResellerId<
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersGivenByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get Total Ownership Transfers Given By Reseller Id
 */

export function useGetTotalOwnershipTransfersGivenByResellerId<
  TData = Awaited<
    ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>
  >,
  TError = ErrorType<void>
>(
  id: string,
  paramsDto: ParamsDto,
  params?: GetTotalOwnershipTransfersGivenByResellerIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTotalOwnershipTransfersGivenByResellerId>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions =
    getGetTotalOwnershipTransfersGivenByResellerIdQueryOptions(
      id,
      paramsDto,
      params,
      options
    )

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
