/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'

import type { InventoryProductModelDto, ParamsDto } from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get current inventory for a reseller
 */
export type resellerInventoryKpiGetCurrentInventoryResponse200 = {
  data: InventoryProductModelDto[]
  status: 200
}

export type resellerInventoryKpiGetCurrentInventoryResponse401 = {
  data: void
  status: 401
}

export type resellerInventoryKpiGetCurrentInventoryResponse403 = {
  data: void
  status: 403
}

export type resellerInventoryKpiGetCurrentInventoryResponseSuccess =
  resellerInventoryKpiGetCurrentInventoryResponse200 & {
    headers: Headers
  }
export type resellerInventoryKpiGetCurrentInventoryResponseError = (
  | resellerInventoryKpiGetCurrentInventoryResponse401
  | resellerInventoryKpiGetCurrentInventoryResponse403
) & {
  headers: Headers
}

export type resellerInventoryKpiGetCurrentInventoryResponse =
  | resellerInventoryKpiGetCurrentInventoryResponseSuccess
  | resellerInventoryKpiGetCurrentInventoryResponseError

export const getResellerInventoryKpiGetCurrentInventoryUrl = () => {
  return `/kpi/my-space/inventory/current`
}

export const resellerInventoryKpiGetCurrentInventory = async (
  paramsDto: ParamsDto,
  options?: RequestInit
): Promise<resellerInventoryKpiGetCurrentInventoryResponse> => {
  return customInstance<resellerInventoryKpiGetCurrentInventoryResponse>(
    getResellerInventoryKpiGetCurrentInventoryUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getResellerInventoryKpiGetCurrentInventoryMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resellerInventoryKpiGetCurrentInventory>>,
    TError,
    { data: ParamsDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof resellerInventoryKpiGetCurrentInventory>>,
  TError,
  { data: ParamsDto },
  TContext
> => {
  const mutationKey = ['resellerInventoryKpiGetCurrentInventory']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resellerInventoryKpiGetCurrentInventory>>,
    { data: ParamsDto }
  > = (props) => {
    const { data } = props ?? {}

    return resellerInventoryKpiGetCurrentInventory(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResellerInventoryKpiGetCurrentInventoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof resellerInventoryKpiGetCurrentInventory>>
>
export type ResellerInventoryKpiGetCurrentInventoryMutationBody = ParamsDto
export type ResellerInventoryKpiGetCurrentInventoryMutationError =
  ErrorType<void>

/**
 * @summary Get current inventory for a reseller
 */
export const useResellerInventoryKpiGetCurrentInventory = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resellerInventoryKpiGetCurrentInventory>>,
      TError,
      { data: ParamsDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof resellerInventoryKpiGetCurrentInventory>>,
  TError,
  { data: ParamsDto },
  TContext
> => {
  return useMutation(
    getResellerInventoryKpiGetCurrentInventoryMutationOptions(options),
    queryClient
  )
}
