/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'

import type { GetInventoryByIdReturnDto } from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get inventory by ID
 */
export type getInventoryByIdResponse200 = {
  data: GetInventoryByIdReturnDto
  status: 200
}

export type getInventoryByIdResponse401 = {
  data: void
  status: 401
}

export type getInventoryByIdResponse403 = {
  data: void
  status: 403
}

export type getInventoryByIdResponseSuccess = getInventoryByIdResponse200 & {
  headers: Headers
}
export type getInventoryByIdResponseError = (
  | getInventoryByIdResponse401
  | getInventoryByIdResponse403
) & {
  headers: Headers
}

export type getInventoryByIdResponse =
  | getInventoryByIdResponseSuccess
  | getInventoryByIdResponseError

export const getGetInventoryByIdUrl = (id: string) => {
  return `/inventory/${id}`
}

export const getInventoryById = async (
  id: string,
  options?: RequestInit
): Promise<getInventoryByIdResponse> => {
  return customInstance<getInventoryByIdResponse>(getGetInventoryByIdUrl(id), {
    ...options,
    method: 'GET'
  })
}

export const getGetInventoryByIdQueryKey = (id: string) => {
  return [`/inventory/${id}`] as const
}

export const getGetInventoryByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getInventoryById>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventoryById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetInventoryByIdQueryKey(id)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getInventoryById>>
  > = ({ signal }) => getInventoryById(id, { signal, ...requestOptions })

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getInventoryById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInventoryByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getInventoryById>>
>
export type GetInventoryByIdQueryError = ErrorType<void>

export function useGetInventoryById<
  TData = Awaited<ReturnType<typeof getInventoryById>>,
  TError = ErrorType<void>
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventoryById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInventoryById>>,
          TError,
          Awaited<ReturnType<typeof getInventoryById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInventoryById<
  TData = Awaited<ReturnType<typeof getInventoryById>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventoryById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInventoryById>>,
          TError,
          Awaited<ReturnType<typeof getInventoryById>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetInventoryById<
  TData = Awaited<ReturnType<typeof getInventoryById>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventoryById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get inventory by ID
 */

export function useGetInventoryById<
  TData = Awaited<ReturnType<typeof getInventoryById>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getInventoryById>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>
} {
  const queryOptions = getGetInventoryByIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}
