/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Luxis API
 * System API for Luxis
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'

import type { MonthlySalesDto, ParamsDto } from '../model'

import { customInstance } from '../../lib/orval-mutator'
import type { ErrorType } from '../../lib/orval-mutator'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get monthly sales for a reseller
 */
export type resellerSaleKpiGetMonthlySalesResponse200 = {
  data: MonthlySalesDto[]
  status: 200
}

export type resellerSaleKpiGetMonthlySalesResponse401 = {
  data: void
  status: 401
}

export type resellerSaleKpiGetMonthlySalesResponse403 = {
  data: void
  status: 403
}

export type resellerSaleKpiGetMonthlySalesResponseSuccess =
  resellerSaleKpiGetMonthlySalesResponse200 & {
    headers: Headers
  }
export type resellerSaleKpiGetMonthlySalesResponseError = (
  | resellerSaleKpiGetMonthlySalesResponse401
  | resellerSaleKpiGetMonthlySalesResponse403
) & {
  headers: Headers
}

export type resellerSaleKpiGetMonthlySalesResponse =
  | resellerSaleKpiGetMonthlySalesResponseSuccess
  | resellerSaleKpiGetMonthlySalesResponseError

export const getResellerSaleKpiGetMonthlySalesUrl = () => {
  return `/kpi/my-space/sales/monthly`
}

export const resellerSaleKpiGetMonthlySales = async (
  paramsDto: ParamsDto,
  options?: RequestInit
): Promise<resellerSaleKpiGetMonthlySalesResponse> => {
  return customInstance<resellerSaleKpiGetMonthlySalesResponse>(
    getResellerSaleKpiGetMonthlySalesUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getResellerSaleKpiGetMonthlySalesMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resellerSaleKpiGetMonthlySales>>,
    TError,
    { data: ParamsDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof resellerSaleKpiGetMonthlySales>>,
  TError,
  { data: ParamsDto },
  TContext
> => {
  const mutationKey = ['resellerSaleKpiGetMonthlySales']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resellerSaleKpiGetMonthlySales>>,
    { data: ParamsDto }
  > = (props) => {
    const { data } = props ?? {}

    return resellerSaleKpiGetMonthlySales(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResellerSaleKpiGetMonthlySalesMutationResult = NonNullable<
  Awaited<ReturnType<typeof resellerSaleKpiGetMonthlySales>>
>
export type ResellerSaleKpiGetMonthlySalesMutationBody = ParamsDto
export type ResellerSaleKpiGetMonthlySalesMutationError = ErrorType<void>

/**
 * @summary Get monthly sales for a reseller
 */
export const useResellerSaleKpiGetMonthlySales = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resellerSaleKpiGetMonthlySales>>,
      TError,
      { data: ParamsDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof resellerSaleKpiGetMonthlySales>>,
  TError,
  { data: ParamsDto },
  TContext
> => {
  return useMutation(
    getResellerSaleKpiGetMonthlySalesMutationOptions(options),
    queryClient
  )
}
/**
 * @summary Get average ticket for a reseller
 */
export type resellerSaleKpiGetAverageTicketResponse200 = {
  data: number
  status: 200
}

export type resellerSaleKpiGetAverageTicketResponse401 = {
  data: void
  status: 401
}

export type resellerSaleKpiGetAverageTicketResponse403 = {
  data: void
  status: 403
}

export type resellerSaleKpiGetAverageTicketResponseSuccess =
  resellerSaleKpiGetAverageTicketResponse200 & {
    headers: Headers
  }
export type resellerSaleKpiGetAverageTicketResponseError = (
  | resellerSaleKpiGetAverageTicketResponse401
  | resellerSaleKpiGetAverageTicketResponse403
) & {
  headers: Headers
}

export type resellerSaleKpiGetAverageTicketResponse =
  | resellerSaleKpiGetAverageTicketResponseSuccess
  | resellerSaleKpiGetAverageTicketResponseError

export const getResellerSaleKpiGetAverageTicketUrl = () => {
  return `/kpi/my-space/sales/average-ticket`
}

export const resellerSaleKpiGetAverageTicket = async (
  paramsDto: ParamsDto,
  options?: RequestInit
): Promise<resellerSaleKpiGetAverageTicketResponse> => {
  return customInstance<resellerSaleKpiGetAverageTicketResponse>(
    getResellerSaleKpiGetAverageTicketUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(paramsDto)
    }
  )
}

export const getResellerSaleKpiGetAverageTicketMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resellerSaleKpiGetAverageTicket>>,
    TError,
    { data: ParamsDto },
    TContext
  >
  request?: SecondParameter<typeof customInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof resellerSaleKpiGetAverageTicket>>,
  TError,
  { data: ParamsDto },
  TContext
> => {
  const mutationKey = ['resellerSaleKpiGetAverageTicket']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resellerSaleKpiGetAverageTicket>>,
    { data: ParamsDto }
  > = (props) => {
    const { data } = props ?? {}

    return resellerSaleKpiGetAverageTicket(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResellerSaleKpiGetAverageTicketMutationResult = NonNullable<
  Awaited<ReturnType<typeof resellerSaleKpiGetAverageTicket>>
>
export type ResellerSaleKpiGetAverageTicketMutationBody = ParamsDto
export type ResellerSaleKpiGetAverageTicketMutationError = ErrorType<void>

/**
 * @summary Get average ticket for a reseller
 */
export const useResellerSaleKpiGetAverageTicket = <
  TError = ErrorType<void>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resellerSaleKpiGetAverageTicket>>,
      TError,
      { data: ParamsDto },
      TContext
    >
    request?: SecondParameter<typeof customInstance>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof resellerSaleKpiGetAverageTicket>>,
  TError,
  { data: ParamsDto },
  TContext
> => {
  return useMutation(
    getResellerSaleKpiGetAverageTicketMutationOptions(options),
    queryClient
  )
}
